/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ScrapeBadger.Model;
using ScrapeBadger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ScrapeBadger.Test.Model
{
    /// <summary>
    ///  Class for testing AccountInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccountInfo
        //private AccountInfo instance;

        public AccountInfoTests()
        {
            // TODO uncomment below to create an instance of AccountInfo
            //instance = new AccountInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountInfo
        /// </summary>
        [Fact]
        public void AccountInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccountInfo
            //Assert.IsType<AccountInfo>(instance);
        }

        /// <summary>
        /// Test the property 'CreditsBalance'
        /// </summary>
        [Fact]
        public void CreditsBalanceTest()
        {
            // TODO unit test for the property 'CreditsBalance'
        }

        /// <summary>
        /// Test the property 'SubscriptionCreditsBalance'
        /// </summary>
        [Fact]
        public void SubscriptionCreditsBalanceTest()
        {
            // TODO unit test for the property 'SubscriptionCreditsBalance'
        }

        /// <summary>
        /// Test the property 'TotalCreditsBalance'
        /// </summary>
        [Fact]
        public void TotalCreditsBalanceTest()
        {
            // TODO unit test for the property 'TotalCreditsBalance'
        }

        /// <summary>
        /// Test the property 'Tier'
        /// </summary>
        [Fact]
        public void TierTest()
        {
            // TODO unit test for the property 'Tier'
        }

        /// <summary>
        /// Test the property 'RateLimitPerMinute'
        /// </summary>
        [Fact]
        public void RateLimitPerMinuteTest()
        {
            // TODO unit test for the property 'RateLimitPerMinute'
        }

        /// <summary>
        /// Test the property 'Subscription'
        /// </summary>
        [Fact]
        public void SubscriptionTest()
        {
            // TODO unit test for the property 'Subscription'
        }
    }
}
