/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ScrapeBadger.Model;
using ScrapeBadger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ScrapeBadger.Test.Model
{
    /// <summary>
    ///  Class for testing BillingLogResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BillingLogResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BillingLogResponse
        //private BillingLogResponse instance;

        public BillingLogResponseTests()
        {
            // TODO uncomment below to create an instance of BillingLogResponse
            //instance = new BillingLogResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BillingLogResponse
        /// </summary>
        [Fact]
        public void BillingLogResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" BillingLogResponse
            //Assert.IsType<BillingLogResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'MonitorId'
        /// </summary>
        [Fact]
        public void MonitorIdTest()
        {
            // TODO unit test for the property 'MonitorId'
        }

        /// <summary>
        /// Test the property 'MonitorName'
        /// </summary>
        [Fact]
        public void MonitorNameTest()
        {
            // TODO unit test for the property 'MonitorName'
        }

        /// <summary>
        /// Test the property 'BilledAt'
        /// </summary>
        [Fact]
        public void BilledAtTest()
        {
            // TODO unit test for the property 'BilledAt'
        }

        /// <summary>
        /// Test the property 'NumAccounts'
        /// </summary>
        [Fact]
        public void NumAccountsTest()
        {
            // TODO unit test for the property 'NumAccounts'
        }

        /// <summary>
        /// Test the property 'CreditsDeducted'
        /// </summary>
        [Fact]
        public void CreditsDeductedTest()
        {
            // TODO unit test for the property 'CreditsDeducted'
        }

        /// <summary>
        /// Test the property 'TierLabel'
        /// </summary>
        [Fact]
        public void TierLabelTest()
        {
            // TODO unit test for the property 'TierLabel'
        }

        /// <summary>
        /// Test the property 'RateApplied'
        /// </summary>
        [Fact]
        public void RateAppliedTest()
        {
            // TODO unit test for the property 'RateApplied'
        }
    }
}
