/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ScrapeBadger.Model;
using ScrapeBadger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ScrapeBadger.Test.Model
{
    /// <summary>
    ///  Class for testing ExtractRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExtractRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExtractRequest
        //private ExtractRequest instance;

        public ExtractRequestTests()
        {
            // TODO uncomment below to create an instance of ExtractRequest
            //instance = new ExtractRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExtractRequest
        /// </summary>
        [Fact]
        public void ExtractRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExtractRequest
            //Assert.IsType<ExtractRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'WaitFor'
        /// </summary>
        [Fact]
        public void WaitForTest()
        {
            // TODO unit test for the property 'WaitFor'
        }

        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

        /// <summary>
        /// Test the property 'ProxyTier'
        /// </summary>
        [Fact]
        public void ProxyTierTest()
        {
            // TODO unit test for the property 'ProxyTier'
        }

        /// <summary>
        /// Test the property 'ExtractRules'
        /// </summary>
        [Fact]
        public void ExtractRulesTest()
        {
            // TODO unit test for the property 'ExtractRules'
        }

        /// <summary>
        /// Test the property 'AiExtractRules'
        /// </summary>
        [Fact]
        public void AiExtractRulesTest()
        {
            // TODO unit test for the property 'AiExtractRules'
        }

        /// <summary>
        /// Test the property 'AiQuery'
        /// </summary>
        [Fact]
        public void AiQueryTest()
        {
            // TODO unit test for the property 'AiQuery'
        }

        /// <summary>
        /// Test the property 'RenderJs'
        /// </summary>
        [Fact]
        public void RenderJsTest()
        {
            // TODO unit test for the property 'RenderJs'
        }
    }
}
