/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ScrapeBadger.Model;
using ScrapeBadger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ScrapeBadger.Test.Model
{
    /// <summary>
    ///  Class for testing FilterRuleValidateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FilterRuleValidateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FilterRuleValidateRequest
        //private FilterRuleValidateRequest instance;

        public FilterRuleValidateRequestTests()
        {
            // TODO uncomment below to create an instance of FilterRuleValidateRequest
            //instance = new FilterRuleValidateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FilterRuleValidateRequest
        /// </summary>
        [Fact]
        public void FilterRuleValidateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" FilterRuleValidateRequest
            //Assert.IsType<FilterRuleValidateRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Fact]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }
    }
}
