/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ScrapeBadger.Model;
using ScrapeBadger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ScrapeBadger.Test.Model
{
    /// <summary>
    ///  Class for testing FilterRuleUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FilterRuleUpdateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FilterRuleUpdate
        //private FilterRuleUpdate instance;

        public FilterRuleUpdateTests()
        {
            // TODO uncomment below to create an instance of FilterRuleUpdate
            //instance = new FilterRuleUpdate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FilterRuleUpdate
        /// </summary>
        [Fact]
        public void FilterRuleUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsType" FilterRuleUpdate
            //Assert.IsType<FilterRuleUpdate>(instance);
        }

        /// <summary>
        /// Test the property 'Tag'
        /// </summary>
        [Fact]
        public void TagTest()
        {
            // TODO unit test for the property 'Tag'
        }

        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Fact]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }

        /// <summary>
        /// Test the property 'IntervalSeconds'
        /// </summary>
        [Fact]
        public void IntervalSecondsTest()
        {
            // TODO unit test for the property 'IntervalSeconds'
        }

        /// <summary>
        /// Test the property 'MaxResultsPerPoll'
        /// </summary>
        [Fact]
        public void MaxResultsPerPollTest()
        {
            // TODO unit test for the property 'MaxResultsPerPoll'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'WebhookUrl'
        /// </summary>
        [Fact]
        public void WebhookUrlTest()
        {
            // TODO unit test for the property 'WebhookUrl'
        }

        /// <summary>
        /// Test the property 'WebhookSecret'
        /// </summary>
        [Fact]
        public void WebhookSecretTest()
        {
            // TODO unit test for the property 'WebhookSecret'
        }
    }
}
