/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ScrapeBadger.Model;
using ScrapeBadger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ScrapeBadger.Test.Model
{
    /// <summary>
    ///  Class for testing PortalApiRoutersV1TwitterFilterRulesFilterRulePricingResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PortalApiRoutersV1TwitterFilterRulesFilterRulePricingResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PortalApiRoutersV1TwitterFilterRulesFilterRulePricingResponse
        //private PortalApiRoutersV1TwitterFilterRulesFilterRulePricingResponse instance;

        public PortalApiRoutersV1TwitterFilterRulesFilterRulePricingResponseTests()
        {
            // TODO uncomment below to create an instance of PortalApiRoutersV1TwitterFilterRulesFilterRulePricingResponse
            //instance = new PortalApiRoutersV1TwitterFilterRulesFilterRulePricingResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PortalApiRoutersV1TwitterFilterRulesFilterRulePricingResponse
        /// </summary>
        [Fact]
        public void PortalApiRoutersV1TwitterFilterRulesFilterRulePricingResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PortalApiRoutersV1TwitterFilterRulesFilterRulePricingResponse
            //Assert.IsType<PortalApiRoutersV1TwitterFilterRulesFilterRulePricingResponse>(instance);
        }

        /// <summary>
        /// Test the property 'CreditsPerEmptyCall'
        /// </summary>
        [Fact]
        public void CreditsPerEmptyCallTest()
        {
            // TODO unit test for the property 'CreditsPerEmptyCall'
        }

        /// <summary>
        /// Test the property 'CreditsPerTweetReturned'
        /// </summary>
        [Fact]
        public void CreditsPerTweetReturnedTest()
        {
            // TODO unit test for the property 'CreditsPerTweetReturned'
        }
    }
}
