/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ScrapeBadger.Model;
using ScrapeBadger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ScrapeBadger.Test.Model
{
    /// <summary>
    ///  Class for testing StreamMonitorCreate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StreamMonitorCreateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StreamMonitorCreate
        //private StreamMonitorCreate instance;

        public StreamMonitorCreateTests()
        {
            // TODO uncomment below to create an instance of StreamMonitorCreate
            //instance = new StreamMonitorCreate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StreamMonitorCreate
        /// </summary>
        [Fact]
        public void StreamMonitorCreateInstanceTest()
        {
            // TODO uncomment below to test "IsType" StreamMonitorCreate
            //Assert.IsType<StreamMonitorCreate>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Usernames'
        /// </summary>
        [Fact]
        public void UsernamesTest()
        {
            // TODO unit test for the property 'Usernames'
        }

        /// <summary>
        /// Test the property 'WebhookUrl'
        /// </summary>
        [Fact]
        public void WebhookUrlTest()
        {
            // TODO unit test for the property 'WebhookUrl'
        }

        /// <summary>
        /// Test the property 'WebhookSecret'
        /// </summary>
        [Fact]
        public void WebhookSecretTest()
        {
            // TODO unit test for the property 'WebhookSecret'
        }

        /// <summary>
        /// Test the property 'FilterTypes'
        /// </summary>
        [Fact]
        public void FilterTypesTest()
        {
            // TODO unit test for the property 'FilterTypes'
        }
    }
}
