/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ScrapeBadger.Model;
using ScrapeBadger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ScrapeBadger.Test.Model
{
    /// <summary>
    ///  Class for testing VintedMobileReadRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VintedMobileReadRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VintedMobileReadRequest
        //private VintedMobileReadRequest instance;

        public VintedMobileReadRequestTests()
        {
            // TODO uncomment below to create an instance of VintedMobileReadRequest
            //instance = new VintedMobileReadRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VintedMobileReadRequest
        /// </summary>
        [Fact]
        public void VintedMobileReadRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" VintedMobileReadRequest
            //Assert.IsType<VintedMobileReadRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Market'
        /// </summary>
        [Fact]
        public void MarketTest()
        {
            // TODO unit test for the property 'Market'
        }

        /// <summary>
        /// Test the property 'Parameters'
        /// </summary>
        [Fact]
        public void ParametersTest()
        {
            // TODO unit test for the property 'Parameters'
        }
    }
}
