/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ScrapeBadger.Model;
using ScrapeBadger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ScrapeBadger.Test.Model
{
    /// <summary>
    ///  Class for testing VintedItemSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VintedItemSummaryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VintedItemSummary
        //private VintedItemSummary instance;

        public VintedItemSummaryTests()
        {
            // TODO uncomment below to create an instance of VintedItemSummary
            //instance = new VintedItemSummary();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VintedItemSummary
        /// </summary>
        [Fact]
        public void VintedItemSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsType" VintedItemSummary
            //Assert.IsType<VintedItemSummary>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }

        /// <summary>
        /// Test the property 'BrandTitle'
        /// </summary>
        [Fact]
        public void BrandTitleTest()
        {
            // TODO unit test for the property 'BrandTitle'
        }

        /// <summary>
        /// Test the property 'DisplayTitle'
        /// </summary>
        [Fact]
        public void DisplayTitleTest()
        {
            // TODO unit test for the property 'DisplayTitle'
        }

        /// <summary>
        /// Test the property 'DisplaySubtitle'
        /// </summary>
        [Fact]
        public void DisplaySubtitleTest()
        {
            // TODO unit test for the property 'DisplaySubtitle'
        }

        /// <summary>
        /// Test the property 'SizeTitle'
        /// </summary>
        [Fact]
        public void SizeTitleTest()
        {
            // TODO unit test for the property 'SizeTitle'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Fact]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }

        /// <summary>
        /// Test the property 'IsVisible'
        /// </summary>
        [Fact]
        public void IsVisibleTest()
        {
            // TODO unit test for the property 'IsVisible'
        }

        /// <summary>
        /// Test the property 'Promoted'
        /// </summary>
        [Fact]
        public void PromotedTest()
        {
            // TODO unit test for the property 'Promoted'
        }

        /// <summary>
        /// Test the property 'FavouriteCount'
        /// </summary>
        [Fact]
        public void FavouriteCountTest()
        {
            // TODO unit test for the property 'FavouriteCount'
        }

        /// <summary>
        /// Test the property 'ViewCount'
        /// </summary>
        [Fact]
        public void ViewCountTest()
        {
            // TODO unit test for the property 'ViewCount'
        }

        /// <summary>
        /// Test the property 'ServiceFee'
        /// </summary>
        [Fact]
        public void ServiceFeeTest()
        {
            // TODO unit test for the property 'ServiceFee'
        }

        /// <summary>
        /// Test the property 'TotalItemPrice'
        /// </summary>
        [Fact]
        public void TotalItemPriceTest()
        {
            // TODO unit test for the property 'TotalItemPrice'
        }

        /// <summary>
        /// Test the property 'ContentSource'
        /// </summary>
        [Fact]
        public void ContentSourceTest()
        {
            // TODO unit test for the property 'ContentSource'
        }

        /// <summary>
        /// Test the property 'SellerCountryCode'
        /// </summary>
        [Fact]
        public void SellerCountryCodeTest()
        {
            // TODO unit test for the property 'SellerCountryCode'
        }

        /// <summary>
        /// Test the property 'SimilarityScore'
        /// </summary>
        [Fact]
        public void SimilarityScoreTest()
        {
            // TODO unit test for the property 'SimilarityScore'
        }

        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }

        /// <summary>
        /// Test the property 'Photo'
        /// </summary>
        [Fact]
        public void PhotoTest()
        {
            // TODO unit test for the property 'Photo'
        }

        /// <summary>
        /// Test the property 'Photos'
        /// </summary>
        [Fact]
        public void PhotosTest()
        {
            // TODO unit test for the property 'Photos'
        }
    }
}
