/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ScrapeBadger.Model;
using ScrapeBadger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ScrapeBadger.Test.Model
{
    /// <summary>
    ///  Class for testing VintedBrand
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VintedBrandTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VintedBrand
        //private VintedBrand instance;

        public VintedBrandTests()
        {
            // TODO uncomment below to create an instance of VintedBrand
            //instance = new VintedBrand();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VintedBrand
        /// </summary>
        [Fact]
        public void VintedBrandInstanceTest()
        {
            // TODO uncomment below to test "IsType" VintedBrand
            //Assert.IsType<VintedBrand>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Slug'
        /// </summary>
        [Fact]
        public void SlugTest()
        {
            // TODO unit test for the property 'Slug'
        }

        /// <summary>
        /// Test the property 'ItemCount'
        /// </summary>
        [Fact]
        public void ItemCountTest()
        {
            // TODO unit test for the property 'ItemCount'
        }

        /// <summary>
        /// Test the property 'FavouriteCount'
        /// </summary>
        [Fact]
        public void FavouriteCountTest()
        {
            // TODO unit test for the property 'FavouriteCount'
        }

        /// <summary>
        /// Test the property 'IsLuxury'
        /// </summary>
        [Fact]
        public void IsLuxuryTest()
        {
            // TODO unit test for the property 'IsLuxury'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
    }
}
