/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ScrapeBadger.Model;
using ScrapeBadger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ScrapeBadger.Test.Model
{
    /// <summary>
    ///  Class for testing WebhookTestRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebhookTestRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebhookTestRequest
        //private WebhookTestRequest instance;

        public WebhookTestRequestTests()
        {
            // TODO uncomment below to create an instance of WebhookTestRequest
            //instance = new WebhookTestRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebhookTestRequest
        /// </summary>
        [Fact]
        public void WebhookTestRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebhookTestRequest
            //Assert.IsType<WebhookTestRequest>(instance);
        }

        /// <summary>
        /// Test the property 'MonitorId'
        /// </summary>
        [Fact]
        public void MonitorIdTest()
        {
            // TODO unit test for the property 'MonitorId'
        }
    }
}
