/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using ScrapeBadger.Client;
using ScrapeBadger.Api;
// uncomment below to import models
//using ScrapeBadger.Model;

namespace ScrapeBadger.Test.Api
{
    /// <summary>
    ///  Class for testing AmazonApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AmazonApiTests : IDisposable
    {
        private AmazonApi instance;

        public AmazonApiTests()
        {
            instance = new AmazonApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AmazonApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AmazonApi
            //Assert.IsType<AmazonApi>(instance);
        }

        /// <summary>
        /// Test AmazonAmazonScraperHealthCheck
        /// </summary>
        [Fact]
        public void AmazonAmazonScraperHealthCheckTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.AmazonAmazonScraperHealthCheck();
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test AmazonAmazonScraperHealthCheckHead
        /// </summary>
        [Fact]
        public void AmazonAmazonScraperHealthCheckHeadTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.AmazonAmazonScraperHealthCheckHead();
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test AmazonBestsellersByCategory
        /// </summary>
        [Fact]
        public void AmazonBestsellersByCategoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string domain = null;
            //string category = null;
            //int? page = null;
            //var response = instance.AmazonBestsellersByCategory(domain, category, page);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test AmazonBrowseNodeCategoryListing
        /// </summary>
        [Fact]
        public void AmazonBrowseNodeCategoryListingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string node = null;
            //string domain = null;
            //int? page = null;
            //string sortBy = null;
            //var response = instance.AmazonBrowseNodeCategoryListing(node, domain, page, sortBy);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test AmazonGetAllSellerOffersBuybox
        /// </summary>
        [Fact]
        public void AmazonGetAllSellerOffersBuyboxTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string asin = null;
            //string domain = null;
            //string zip = null;
            //var response = instance.AmazonGetAllSellerOffersBuybox(asin, domain, zip);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test AmazonGetProductDetail
        /// </summary>
        [Fact]
        public void AmazonGetProductDetailTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string asin = null;
            //string domain = null;
            //string zip = null;
            //string language = null;
            //var response = instance.AmazonGetProductDetail(asin, domain, zip, language);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test AmazonGetProductReviews
        /// </summary>
        [Fact]
        public void AmazonGetProductReviewsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string asin = null;
            //string domain = null;
            //int? page = null;
            //string sortBy = null;
            //string star = null;
            //bool? verifiedOnly = null;
            //bool? mediaOnly = null;
            //var response = instance.AmazonGetProductReviews(asin, domain, page, sortBy, star, verifiedOnly, mediaOnly);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test AmazonGetSellerFeedback
        /// </summary>
        [Fact]
        public void AmazonGetSellerFeedbackTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string sellerId = null;
            //string domain = null;
            //int? page = null;
            //var response = instance.AmazonGetSellerFeedback(sellerId, domain, page);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test AmazonGetSellerProfile
        /// </summary>
        [Fact]
        public void AmazonGetSellerProfileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string sellerId = null;
            //string domain = null;
            //var response = instance.AmazonGetSellerProfile(sellerId, domain);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test AmazonGetSellerStorefrontProducts
        /// </summary>
        [Fact]
        public void AmazonGetSellerStorefrontProductsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string sellerId = null;
            //string domain = null;
            //int? page = null;
            //var response = instance.AmazonGetSellerStorefrontProducts(sellerId, domain, page);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test AmazonKeywordSuggestions
        /// </summary>
        [Fact]
        public void AmazonKeywordSuggestionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string query = null;
            //string domain = null;
            //var response = instance.AmazonKeywordSuggestions(query, domain);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test AmazonListCategoryAliases
        /// </summary>
        [Fact]
        public void AmazonListCategoryAliasesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string domain = null;
            //var response = instance.AmazonListCategoryAliases(domain);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test AmazonListMarketplaces
        /// </summary>
        [Fact]
        public void AmazonListMarketplacesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.AmazonListMarketplaces();
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test AmazonNewReleasesByCategory
        /// </summary>
        [Fact]
        public void AmazonNewReleasesByCategoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string domain = null;
            //string category = null;
            //int? page = null;
            //var response = instance.AmazonNewReleasesByCategory(domain, category, page);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test AmazonSearchAmazonProducts
        /// </summary>
        [Fact]
        public void AmazonSearchAmazonProductsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string query = null;
            //string domain = null;
            //int? page = null;
            //string sortBy = null;
            //string category = null;
            //decimal? minPrice = null;
            //decimal? maxPrice = null;
            //string zip = null;
            //string language = null;
            //var response = instance.AmazonSearchAmazonProducts(query, domain, page, sortBy, category, minPrice, maxPrice, zip, language);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test AmazonTodaySDeals
        /// </summary>
        [Fact]
        public void AmazonTodaySDealsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string domain = null;
            //string category = null;
            //int? page = null;
            //var response = instance.AmazonTodaySDeals(domain, category, page);
            //Assert.IsType<Object>(response);
        }
    }
}
