/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using ScrapeBadger.Client;
using ScrapeBadger.Api;
// uncomment below to import models
//using ScrapeBadger.Model;

namespace ScrapeBadger.Test.Api
{
    /// <summary>
    ///  Class for testing BaiduApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class BaiduApiTests : IDisposable
    {
        private BaiduApi instance;

        public BaiduApiTests()
        {
            instance = new BaiduApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BaiduApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' BaiduApi
            //Assert.IsType<BaiduApi>(instance);
        }

        /// <summary>
        /// Test BaiduBaiduImageSearch
        /// </summary>
        [Fact]
        public void BaiduBaiduImageSearchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string query = null;
            //int? page = null;
            //var response = instance.BaiduBaiduImageSearch(query, page);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test BaiduBaiduNewsSearch
        /// </summary>
        [Fact]
        public void BaiduBaiduNewsSearchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string query = null;
            //int? page = null;
            //var response = instance.BaiduBaiduNewsSearch(query, page);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test BaiduBaiduScraperHealthCheck
        /// </summary>
        [Fact]
        public void BaiduBaiduScraperHealthCheckTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.BaiduBaiduScraperHealthCheck();
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test BaiduBaiduScraperHealthCheckHead
        /// </summary>
        [Fact]
        public void BaiduBaiduScraperHealthCheckHeadTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.BaiduBaiduScraperHealthCheckHead();
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test BaiduBaiduWebSearch
        /// </summary>
        [Fact]
        public void BaiduBaiduWebSearchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string query = null;
            //int? page = null;
            //int? num = null;
            //var response = instance.BaiduBaiduWebSearch(query, page, num);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test BaiduSearchSuggestions
        /// </summary>
        [Fact]
        public void BaiduSearchSuggestionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string query = null;
            //var response = instance.BaiduSearchSuggestions(query);
            //Assert.IsType<Object>(response);
        }
    }
}
