/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using ScrapeBadger.Client;
using ScrapeBadger.Api;
// uncomment below to import models
//using ScrapeBadger.Model;

namespace ScrapeBadger.Test.Api
{
    /// <summary>
    ///  Class for testing BingApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class BingApiTests : IDisposable
    {
        private BingApi instance;

        public BingApiTests()
        {
            instance = new BingApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BingApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' BingApi
            //Assert.IsType<BingApi>(instance);
        }

        /// <summary>
        /// Test BingBingScraperHealthCheck
        /// </summary>
        [Fact]
        public void BingBingScraperHealthCheckTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.BingBingScraperHealthCheck();
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test BingBingScraperHealthCheckHead
        /// </summary>
        [Fact]
        public void BingBingScraperHealthCheckHeadTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.BingBingScraperHealthCheckHead();
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test BingImageSearch
        /// </summary>
        [Fact]
        public void BingImageSearchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string query = null;
            //string market = null;
            //int? count = null;
            //string safeSearch = null;
            //var response = instance.BingImageSearch(query, market, count, safeSearch);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test BingListSupportedMarkets
        /// </summary>
        [Fact]
        public void BingListSupportedMarketsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.BingListSupportedMarkets();
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test BingNewsSearch
        /// </summary>
        [Fact]
        public void BingNewsSearchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string query = null;
            //string market = null;
            //string freshness = null;
            //var response = instance.BingNewsSearch(query, market, freshness);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test BingSearchSuggestions
        /// </summary>
        [Fact]
        public void BingSearchSuggestionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string query = null;
            //string market = null;
            //var response = instance.BingSearchSuggestions(query, market);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test BingVideoSearch
        /// </summary>
        [Fact]
        public void BingVideoSearchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string query = null;
            //string market = null;
            //int? count = null;
            //string safeSearch = null;
            //var response = instance.BingVideoSearch(query, market, count, safeSearch);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test BingWebSearch
        /// </summary>
        [Fact]
        public void BingWebSearchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string query = null;
            //string market = null;
            //int? count = null;
            //int? offset = null;
            //string safeSearch = null;
            //var response = instance.BingWebSearch(query, market, count, offset, safeSearch);
            //Assert.IsType<Object>(response);
        }
    }
}
