/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using ScrapeBadger.Client;
using ScrapeBadger.Api;
// uncomment below to import models
//using ScrapeBadger.Model;

namespace ScrapeBadger.Test.Api
{
    /// <summary>
    ///  Class for testing BookingApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class BookingApiTests : IDisposable
    {
        private BookingApi instance;

        public BookingApiTests()
        {
            instance = new BookingApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BookingApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' BookingApi
            //Assert.IsType<BookingApi>(instance);
        }

        /// <summary>
        /// Test BookingBookingScraperHealthCheck
        /// </summary>
        [Fact]
        public void BookingBookingScraperHealthCheckTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.BookingBookingScraperHealthCheck();
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test BookingBookingScraperHealthCheckHead
        /// </summary>
        [Fact]
        public void BookingBookingScraperHealthCheckHeadTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.BookingBookingScraperHealthCheckHead();
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test BookingGetPropertyDetail
        /// </summary>
        [Fact]
        public void BookingGetPropertyDetailTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string countryCode = null;
            //string slug = null;
            //int? photos = null;
            //int? questions = null;
            //string language = null;
            //var response = instance.BookingGetPropertyDetail(countryCode, slug, photos, questions, language);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test BookingGetPropertyReviews
        /// </summary>
        [Fact]
        public void BookingGetPropertyReviewsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string countryCode = null;
            //string slug = null;
            //int? limit = null;
            //int? offset = null;
            //string sort = null;
            //string reviewLanguage = null;
            //string guestType = null;
            //string language = null;
            //var response = instance.BookingGetPropertyReviews(countryCode, slug, limit, offset, sort, reviewLanguage, guestType, language);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test BookingSearchDestinations
        /// </summary>
        [Fact]
        public void BookingSearchDestinationsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string query = null;
            //int? limit = null;
            //string language = null;
            //var response = instance.BookingSearchDestinations(query, limit, language);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test BookingSearchProperties
        /// </summary>
        [Fact]
        public void BookingSearchPropertiesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string location = null;
            //int? destId = null;
            //string destType = null;
            //string checkin = null;
            //string checkout = null;
            //int? adults = null;
            //string children = null;
            //int? rooms = null;
            //int? offset = null;
            //int? limit = null;
            //string sort = null;
            //string filters = null;
            //string currency = null;
            //string language = null;
            //var response = instance.BookingSearchProperties(location, destId, destType, checkin, checkout, adults, children, rooms, offset, limit, sort, filters, currency, language);
            //Assert.IsType<Object>(response);
        }
    }
}
