/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using ScrapeBadger.Client;
using ScrapeBadger.Api;
// uncomment below to import models
//using ScrapeBadger.Model;

namespace ScrapeBadger.Test.Api
{
    /// <summary>
    ///  Class for testing GooglePlayApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class GooglePlayApiTests : IDisposable
    {
        private GooglePlayApi instance;

        public GooglePlayApiTests()
        {
            instance = new GooglePlayApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GooglePlayApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' GooglePlayApi
            //Assert.IsType<GooglePlayApi>(instance);
        }

        /// <summary>
        /// Test GooglePlayBrowseACategory
        /// </summary>
        [Fact]
        public void GooglePlayBrowseACategoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string categoryId = null;
            //string country = null;
            //string lang = null;
            //var response = instance.GooglePlayBrowseACategory(categoryId, country, lang);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test GooglePlayGetAppDetail
        /// </summary>
        [Fact]
        public void GooglePlayGetAppDetailTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string appId = null;
            //string country = null;
            //string lang = null;
            //var response = instance.GooglePlayGetAppDetail(appId, country, lang);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test GooglePlayGetAppPermissions
        /// </summary>
        [Fact]
        public void GooglePlayGetAppPermissionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string appId = null;
            //string lang = null;
            //var response = instance.GooglePlayGetAppPermissions(appId, lang);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test GooglePlayGetAppReviews
        /// </summary>
        [Fact]
        public void GooglePlayGetAppReviewsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string appId = null;
            //string country = null;
            //string lang = null;
            //string sort = null;
            //int? count = null;
            //string pageToken = null;
            //var response = instance.GooglePlayGetAppReviews(appId, country, lang, sort, count, pageToken);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test GooglePlayGetDeveloperApps
        /// </summary>
        [Fact]
        public void GooglePlayGetDeveloperAppsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string developer = null;
            //string country = null;
            //string lang = null;
            //var response = instance.GooglePlayGetDeveloperApps(developer, country, lang);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test GooglePlayGetSimilarApps
        /// </summary>
        [Fact]
        public void GooglePlayGetSimilarAppsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string appId = null;
            //string country = null;
            //string lang = null;
            //var response = instance.GooglePlayGetSimilarApps(appId, country, lang);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test GooglePlayListCategories
        /// </summary>
        [Fact]
        public void GooglePlayListCategoriesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GooglePlayListCategories();
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test GooglePlayListMarkets
        /// </summary>
        [Fact]
        public void GooglePlayListMarketsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GooglePlayListMarkets();
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test GooglePlaySearchApps
        /// </summary>
        [Fact]
        public void GooglePlaySearchAppsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string query = null;
            //string country = null;
            //string lang = null;
            //string price = null;
            //var response = instance.GooglePlaySearchApps(query, country, lang, price);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test GooglePlayTopCharts
        /// </summary>
        [Fact]
        public void GooglePlayTopChartsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string collection = null;
            //string category = null;
            //string country = null;
            //string lang = null;
            //var response = instance.GooglePlayTopCharts(collection, category, country, lang);
            //Assert.IsType<Object>(response);
        }
    }
}
