/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using ScrapeBadger.Client;
using ScrapeBadger.Api;
// uncomment below to import models
//using ScrapeBadger.Model;

namespace ScrapeBadger.Test.Api
{
    /// <summary>
    ///  Class for testing NaverApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class NaverApiTests : IDisposable
    {
        private NaverApi instance;

        public NaverApiTests()
        {
            instance = new NaverApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NaverApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' NaverApi
            //Assert.IsType<NaverApi>(instance);
        }

        /// <summary>
        /// Test NaverNaverBlogSearch
        /// </summary>
        [Fact]
        public void NaverNaverBlogSearchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string query = null;
            //int? page = null;
            //var response = instance.NaverNaverBlogSearch(query, page);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test NaverNaverDatalabShoppingKeywordInsight
        /// </summary>
        [Fact]
        public void NaverNaverDatalabShoppingKeywordInsightTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string categoryId = null;
            //string startDate = null;
            //string endDate = null;
            //string timeUnit = null;
            //int? count = null;
            //var response = instance.NaverNaverDatalabShoppingKeywordInsight(categoryId, startDate, endDate, timeUnit, count);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test NaverNaverNewsSearch
        /// </summary>
        [Fact]
        public void NaverNaverNewsSearchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string query = null;
            //int? page = null;
            //var response = instance.NaverNaverNewsSearch(query, page);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test NaverNaverPlaceDetail
        /// </summary>
        [Fact]
        public void NaverNaverPlaceDetailTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string placeId = null;
            //var response = instance.NaverNaverPlaceDetail(placeId);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test NaverNaverPlaceLocalSearch
        /// </summary>
        [Fact]
        public void NaverNaverPlaceLocalSearchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string query = null;
            //var response = instance.NaverNaverPlaceLocalSearch(query);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test NaverNaverPlaceVisitorReviews
        /// </summary>
        [Fact]
        public void NaverNaverPlaceVisitorReviewsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string placeId = null;
            //var response = instance.NaverNaverPlaceVisitorReviews(placeId);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test NaverNaverScraperHealthCheck
        /// </summary>
        [Fact]
        public void NaverNaverScraperHealthCheckTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.NaverNaverScraperHealthCheck();
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test NaverNaverScraperHealthCheckHead
        /// </summary>
        [Fact]
        public void NaverNaverScraperHealthCheckHeadTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.NaverNaverScraperHealthCheckHead();
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test NaverNaverShoppingBestsellerRankings
        /// </summary>
        [Fact]
        public void NaverNaverShoppingBestsellerRankingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string categoryId = null;
            //string ageType = null;
            //string sortType = null;
            //string periodType = null;
            //var response = instance.NaverNaverShoppingBestsellerRankings(categoryId, ageType, sortType, periodType);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test NaverNaverShoppingCategoryReference
        /// </summary>
        [Fact]
        public void NaverNaverShoppingCategoryReferenceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.NaverNaverShoppingCategoryReference();
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test NaverNaverShoppingTrendingKeywordRankings
        /// </summary>
        [Fact]
        public void NaverNaverShoppingTrendingKeywordRankingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string categoryId = null;
            //string ageType = null;
            //string sortType = null;
            //string periodType = null;
            //var response = instance.NaverNaverShoppingTrendingKeywordRankings(categoryId, ageType, sortType, periodType);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test NaverNaverWebSearch
        /// </summary>
        [Fact]
        public void NaverNaverWebSearchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string query = null;
            //int? page = null;
            //var response = instance.NaverNaverWebSearch(query, page);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test NaverSearchSuggestions
        /// </summary>
        [Fact]
        public void NaverSearchSuggestionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string query = null;
            //var response = instance.NaverSearchSuggestions(query);
            //Assert.IsType<Object>(response);
        }
    }
}
