/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using ScrapeBadger.Client;
using ScrapeBadger.Api;
// uncomment below to import models
//using ScrapeBadger.Model;

namespace ScrapeBadger.Test.Api
{
    /// <summary>
    ///  Class for testing WebApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class WebApiTests : IDisposable
    {
        private WebApi instance;

        public WebApiTests()
        {
            instance = new WebApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' WebApi
            //Assert.IsType<WebApi>(instance);
        }

        /// <summary>
        /// Test WebDetectAntiBotAndCaptchaSystems
        /// </summary>
        [Fact]
        public void WebDetectAntiBotAndCaptchaSystemsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.WebDetectAntiBotAndCaptchaSystems();
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test WebExtractStructuredData
        /// </summary>
        [Fact]
        public void WebExtractStructuredDataTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.WebExtractStructuredData();
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test WebGetBatchJobStatus
        /// </summary>
        [Fact]
        public void WebGetBatchJobStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string jobId = null;
            //var response = instance.WebGetBatchJobStatus(jobId);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test WebPollAnAutoUnblockDiscoveryJob
        /// </summary>
        [Fact]
        public void WebPollAnAutoUnblockDiscoveryJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string jobId = null;
            //var response = instance.WebPollAnAutoUnblockDiscoveryJob(jobId);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test WebScrapeAUrl
        /// </summary>
        [Fact]
        public void WebScrapeAUrlTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.WebScrapeAUrl();
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test WebSubmitBatchScrapingJob
        /// </summary>
        [Fact]
        public void WebSubmitBatchScrapingJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.WebSubmitBatchScrapingJob();
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test WebTakeAScreenshot
        /// </summary>
        [Fact]
        public void WebTakeAScreenshotTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.WebTakeAScreenshot();
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test WebWebScraperHealthCheck
        /// </summary>
        [Fact]
        public void WebWebScraperHealthCheckTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.WebWebScraperHealthCheck();
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test WebWebScraperHealthCheckHead
        /// </summary>
        [Fact]
        public void WebWebScraperHealthCheckHeadTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.WebWebScraperHealthCheckHead();
            //Assert.IsType<Object>(response);
        }
    }
}
