/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using ScrapeBadger.Client;
using ScrapeBadger.Api;
// uncomment below to import models
//using ScrapeBadger.Model;

namespace ScrapeBadger.Test.Api
{
    /// <summary>
    ///  Class for testing ZillowApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ZillowApiTests : IDisposable
    {
        private ZillowApi instance;

        public ZillowApiTests()
        {
            instance = new ZillowApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ZillowApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ZillowApi
            //Assert.IsType<ZillowApi>(instance);
        }

        /// <summary>
        /// Test ZillowGetAgentProfileListings
        /// </summary>
        [Fact]
        public void ZillowGetAgentProfileListingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //string url = null;
            //var response = instance.ZillowGetAgentProfileListings(username, url);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test ZillowGetPropertyDetail
        /// </summary>
        [Fact]
        public void ZillowGetPropertyDetailTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string zpid = null;
            //var response = instance.ZillowGetPropertyDetail(zpid);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test ZillowGetPropertyDetailByUrl
        /// </summary>
        [Fact]
        public void ZillowGetPropertyDetailByUrlTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string url = null;
            //var response = instance.ZillowGetPropertyDetailByUrl(url);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test ZillowListCoverageMarkets
        /// </summary>
        [Fact]
        public void ZillowListCoverageMarketsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ZillowListCoverageMarkets();
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test ZillowRegionAddressSuggestions
        /// </summary>
        [Fact]
        public void ZillowRegionAddressSuggestionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string query = null;
            //var response = instance.ZillowRegionAddressSuggestions(query);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test ZillowSearchProperties
        /// </summary>
        [Fact]
        public void ZillowSearchPropertiesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string location = null;
            //string status = null;
            //int? page = null;
            //string sort = null;
            //int? priceMin = null;
            //int? priceMax = null;
            //int? bedsMin = null;
            //decimal? bathsMin = null;
            //string homeType = null;
            //int? sqftMin = null;
            //int? sqftMax = null;
            //int? lotMin = null;
            //int? lotMax = null;
            //int? yearBuiltMin = null;
            //int? yearBuiltMax = null;
            //int? hoaMax = null;
            //string keywords = null;
            //string daysOn = null;
            //decimal? north = null;
            //decimal? south = null;
            //decimal? east = null;
            //decimal? west = null;
            //var response = instance.ZillowSearchProperties(location, status, page, sort, priceMin, priceMax, bedsMin, bathsMin, homeType, sqftMin, sqftMax, lotMin, lotMax, yearBuiltMin, yearBuiltMax, hoaMax, keywords, daysOn, north, south, east, west);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test ZillowZillowScraperHealthCheck
        /// </summary>
        [Fact]
        public void ZillowZillowScraperHealthCheckTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ZillowZillowScraperHealthCheck();
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test ZillowZillowScraperHealthCheckHead
        /// </summary>
        [Fact]
        public void ZillowZillowScraperHealthCheckHeadTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ZillowZillowScraperHealthCheckHead();
            //Assert.IsType<Object>(response);
        }
    }
}
