/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ScrapeBadger.Client.FileParameter;
using OpenAPIDateConverter = ScrapeBadger.Client.OpenAPIDateConverter;

namespace ScrapeBadger.Model
{
    /// <summary>
    /// Billing activity log entry.
    /// </summary>
    [DataContract(Name = "BillingLogResponse")]
    public partial class BillingLogResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BillingLogResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BillingLogResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BillingLogResponse" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="monitorId">monitorId (required).</param>
        /// <param name="monitorName">monitorName (required).</param>
        /// <param name="billedAt">billedAt (required).</param>
        /// <param name="numAccounts">numAccounts (required).</param>
        /// <param name="creditsDeducted">creditsDeducted (required).</param>
        /// <param name="tierLabel">tierLabel (required).</param>
        /// <param name="rateApplied">rateApplied (required).</param>
        public BillingLogResponse(string id = default(string), string monitorId = default(string), string monitorName = default(string), DateTime billedAt = default(DateTime), int numAccounts = default(int), decimal creditsDeducted = default(decimal), string tierLabel = default(string), decimal rateApplied = default(decimal))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for BillingLogResponse and cannot be null");
            }
            this.Id = id;
            // to ensure "monitorId" is required (not null)
            if (monitorId == null)
            {
                throw new ArgumentNullException("monitorId is a required property for BillingLogResponse and cannot be null");
            }
            this.MonitorId = monitorId;
            // to ensure "monitorName" is required (not null)
            if (monitorName == null)
            {
                throw new ArgumentNullException("monitorName is a required property for BillingLogResponse and cannot be null");
            }
            this.MonitorName = monitorName;
            this.BilledAt = billedAt;
            this.NumAccounts = numAccounts;
            this.CreditsDeducted = creditsDeducted;
            // to ensure "tierLabel" is required (not null)
            if (tierLabel == null)
            {
                throw new ArgumentNullException("tierLabel is a required property for BillingLogResponse and cannot be null");
            }
            this.TierLabel = tierLabel;
            this.RateApplied = rateApplied;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets MonitorId
        /// </summary>
        [DataMember(Name = "monitor_id", IsRequired = true, EmitDefaultValue = true)]
        public string MonitorId { get; set; }

        /// <summary>
        /// Gets or Sets MonitorName
        /// </summary>
        [DataMember(Name = "monitor_name", IsRequired = true, EmitDefaultValue = true)]
        public string MonitorName { get; set; }

        /// <summary>
        /// Gets or Sets BilledAt
        /// </summary>
        [DataMember(Name = "billed_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTime BilledAt { get; set; }

        /// <summary>
        /// Gets or Sets NumAccounts
        /// </summary>
        [DataMember(Name = "num_accounts", IsRequired = true, EmitDefaultValue = true)]
        public int NumAccounts { get; set; }

        /// <summary>
        /// Gets or Sets CreditsDeducted
        /// </summary>
        [DataMember(Name = "credits_deducted", IsRequired = true, EmitDefaultValue = true)]
        public decimal CreditsDeducted { get; set; }

        /// <summary>
        /// Gets or Sets TierLabel
        /// </summary>
        [DataMember(Name = "tier_label", IsRequired = true, EmitDefaultValue = true)]
        public string TierLabel { get; set; }

        /// <summary>
        /// Gets or Sets RateApplied
        /// </summary>
        [DataMember(Name = "rate_applied", IsRequired = true, EmitDefaultValue = true)]
        public decimal RateApplied { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BillingLogResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  MonitorId: ").Append(MonitorId).Append("\n");
            sb.Append("  MonitorName: ").Append(MonitorName).Append("\n");
            sb.Append("  BilledAt: ").Append(BilledAt).Append("\n");
            sb.Append("  NumAccounts: ").Append(NumAccounts).Append("\n");
            sb.Append("  CreditsDeducted: ").Append(CreditsDeducted).Append("\n");
            sb.Append("  TierLabel: ").Append(TierLabel).Append("\n");
            sb.Append("  RateApplied: ").Append(RateApplied).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
