/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ScrapeBadger.Client.FileParameter;
using OpenAPIDateConverter = ScrapeBadger.Client.OpenAPIDateConverter;

namespace ScrapeBadger.Model
{
    /// <summary>
    /// Filter rule response.  Per-poll billing — see &#x60;&#x60;GET /v1/twitter/filter-rules/pricing&#x60;&#x60; for the rates that apply globally to every rule.
    /// </summary>
    [DataContract(Name = "FilterRuleResponse")]
    public partial class FilterRuleResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FilterRuleResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FilterRuleResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FilterRuleResponse" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="tag">tag (required).</param>
        /// <param name="query">query (required).</param>
        /// <param name="intervalSeconds">intervalSeconds (required).</param>
        /// <param name="maxResultsPerPoll">maxResultsPerPoll (required).</param>
        /// <param name="status">status (required).</param>
        /// <param name="statusReason">statusReason (required).</param>
        /// <param name="webhookUrl">webhookUrl (required).</param>
        /// <param name="webhookSecretSet">webhookSecretSet (required).</param>
        /// <param name="totalCreditsBurned">totalCreditsBurned (required).</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="updatedAt">updatedAt (required).</param>
        public FilterRuleResponse(string id = default(string), string tag = default(string), string query = default(string), decimal intervalSeconds = default(decimal), int maxResultsPerPoll = default(int), string status = default(string), string statusReason = default(string), string webhookUrl = default(string), bool webhookSecretSet = default(bool), decimal totalCreditsBurned = default(decimal), DateTime createdAt = default(DateTime), DateTime updatedAt = default(DateTime))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for FilterRuleResponse and cannot be null");
            }
            this.Id = id;
            // to ensure "tag" is required (not null)
            if (tag == null)
            {
                throw new ArgumentNullException("tag is a required property for FilterRuleResponse and cannot be null");
            }
            this.Tag = tag;
            // to ensure "query" is required (not null)
            if (query == null)
            {
                throw new ArgumentNullException("query is a required property for FilterRuleResponse and cannot be null");
            }
            this.Query = query;
            this.IntervalSeconds = intervalSeconds;
            this.MaxResultsPerPoll = maxResultsPerPoll;
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for FilterRuleResponse and cannot be null");
            }
            this.Status = status;
            // to ensure "statusReason" is required (not null)
            if (statusReason == null)
            {
                throw new ArgumentNullException("statusReason is a required property for FilterRuleResponse and cannot be null");
            }
            this.StatusReason = statusReason;
            // to ensure "webhookUrl" is required (not null)
            if (webhookUrl == null)
            {
                throw new ArgumentNullException("webhookUrl is a required property for FilterRuleResponse and cannot be null");
            }
            this.WebhookUrl = webhookUrl;
            this.WebhookSecretSet = webhookSecretSet;
            this.TotalCreditsBurned = totalCreditsBurned;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Tag
        /// </summary>
        [DataMember(Name = "tag", IsRequired = true, EmitDefaultValue = true)]
        public string Tag { get; set; }

        /// <summary>
        /// Gets or Sets Query
        /// </summary>
        [DataMember(Name = "query", IsRequired = true, EmitDefaultValue = true)]
        public string Query { get; set; }

        /// <summary>
        /// Gets or Sets IntervalSeconds
        /// </summary>
        [DataMember(Name = "interval_seconds", IsRequired = true, EmitDefaultValue = true)]
        public decimal IntervalSeconds { get; set; }

        /// <summary>
        /// Gets or Sets MaxResultsPerPoll
        /// </summary>
        [DataMember(Name = "max_results_per_poll", IsRequired = true, EmitDefaultValue = true)]
        public int MaxResultsPerPoll { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets StatusReason
        /// </summary>
        [DataMember(Name = "status_reason", IsRequired = true, EmitDefaultValue = true)]
        public string StatusReason { get; set; }

        /// <summary>
        /// Gets or Sets WebhookUrl
        /// </summary>
        [DataMember(Name = "webhook_url", IsRequired = true, EmitDefaultValue = true)]
        public string WebhookUrl { get; set; }

        /// <summary>
        /// Gets or Sets WebhookSecretSet
        /// </summary>
        [DataMember(Name = "webhook_secret_set", IsRequired = true, EmitDefaultValue = true)]
        public bool WebhookSecretSet { get; set; }

        /// <summary>
        /// Gets or Sets TotalCreditsBurned
        /// </summary>
        [DataMember(Name = "total_credits_burned", IsRequired = true, EmitDefaultValue = true)]
        public decimal TotalCreditsBurned { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "created_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [DataMember(Name = "updated_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FilterRuleResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Tag: ").Append(Tag).Append("\n");
            sb.Append("  Query: ").Append(Query).Append("\n");
            sb.Append("  IntervalSeconds: ").Append(IntervalSeconds).Append("\n");
            sb.Append("  MaxResultsPerPoll: ").Append(MaxResultsPerPoll).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  StatusReason: ").Append(StatusReason).Append("\n");
            sb.Append("  WebhookUrl: ").Append(WebhookUrl).Append("\n");
            sb.Append("  WebhookSecretSet: ").Append(WebhookSecretSet).Append("\n");
            sb.Append("  TotalCreditsBurned: ").Append(TotalCreditsBurned).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
