/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ScrapeBadger.Client.FileParameter;
using OpenAPIDateConverter = ScrapeBadger.Client.OpenAPIDateConverter;

namespace ScrapeBadger.Model
{
    /// <summary>
    /// Envelope returned by the market reference endpoint.
    /// </summary>
    [DataContract(Name = "MarketsResponse")]
    public partial class MarketsResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MarketsResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MarketsResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MarketsResponse" /> class.
        /// </summary>
        /// <param name="markets">markets (required).</param>
        public MarketsResponse(List<Dictionary<string, Object>> markets = default(List<Dictionary<string, Object>>))
        {
            // to ensure "markets" is required (not null)
            if (markets == null)
            {
                throw new ArgumentNullException("markets is a required property for MarketsResponse and cannot be null");
            }
            this.Markets = markets;
        }

        /// <summary>
        /// Gets or Sets Markets
        /// </summary>
        [DataMember(Name = "markets", IsRequired = true, EmitDefaultValue = true)]
        public List<Dictionary<string, Object>> Markets { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MarketsResponse {\n");
            sb.Append("  Markets: ").Append(Markets).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
