/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ScrapeBadger.Client.FileParameter;
using OpenAPIDateConverter = ScrapeBadger.Client.OpenAPIDateConverter;

namespace ScrapeBadger.Model
{
    /// <summary>
    /// Per-poll rates for filter rules (no tiers — usage-based).
    /// </summary>
    [DataContract(Name = "portal_api__routers__v1_twitter_filter_rules__FilterRulePricingResponse")]
    public partial class PortalApiRoutersV1TwitterFilterRulesFilterRulePricingResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PortalApiRoutersV1TwitterFilterRulesFilterRulePricingResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PortalApiRoutersV1TwitterFilterRulesFilterRulePricingResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PortalApiRoutersV1TwitterFilterRulesFilterRulePricingResponse" /> class.
        /// </summary>
        /// <param name="creditsPerEmptyCall">creditsPerEmptyCall (required).</param>
        /// <param name="creditsPerTweetReturned">creditsPerTweetReturned (required).</param>
        public PortalApiRoutersV1TwitterFilterRulesFilterRulePricingResponse(decimal creditsPerEmptyCall = default(decimal), decimal creditsPerTweetReturned = default(decimal))
        {
            this.CreditsPerEmptyCall = creditsPerEmptyCall;
            this.CreditsPerTweetReturned = creditsPerTweetReturned;
        }

        /// <summary>
        /// Gets or Sets CreditsPerEmptyCall
        /// </summary>
        [DataMember(Name = "credits_per_empty_call", IsRequired = true, EmitDefaultValue = true)]
        public decimal CreditsPerEmptyCall { get; set; }

        /// <summary>
        /// Gets or Sets CreditsPerTweetReturned
        /// </summary>
        [DataMember(Name = "credits_per_tweet_returned", IsRequired = true, EmitDefaultValue = true)]
        public decimal CreditsPerTweetReturned { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PortalApiRoutersV1TwitterFilterRulesFilterRulePricingResponse {\n");
            sb.Append("  CreditsPerEmptyCall: ").Append(CreditsPerEmptyCall).Append("\n");
            sb.Append("  CreditsPerTweetReturned: ").Append(CreditsPerTweetReturned).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
