/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ScrapeBadger.Client.FileParameter;
using OpenAPIDateConverter = ScrapeBadger.Client.OpenAPIDateConverter;

namespace ScrapeBadger.Model
{
    /// <summary>
    /// Create stream monitor request.
    /// </summary>
    [DataContract(Name = "StreamMonitorCreate")]
    public partial class StreamMonitorCreate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StreamMonitorCreate" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected StreamMonitorCreate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="StreamMonitorCreate" /> class.
        /// </summary>
        /// <param name="name">name (required).</param>
        /// <param name="usernames">usernames (required).</param>
        /// <param name="webhookUrl">webhookUrl.</param>
        /// <param name="webhookSecret">webhookSecret.</param>
        /// <param name="filterTypes">filterTypes.</param>
        public StreamMonitorCreate(string name = default(string), List<string> usernames = default(List<string>), string webhookUrl = default(string), string webhookSecret = default(string), List<string> filterTypes = default(List<string>))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for StreamMonitorCreate and cannot be null");
            }
            this.Name = name;
            // to ensure "usernames" is required (not null)
            if (usernames == null)
            {
                throw new ArgumentNullException("usernames is a required property for StreamMonitorCreate and cannot be null");
            }
            this.Usernames = usernames;
            this.WebhookUrl = webhookUrl;
            this.WebhookSecret = webhookSecret;
            this.FilterTypes = filterTypes;
        }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Usernames
        /// </summary>
        [DataMember(Name = "usernames", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Usernames { get; set; }

        /// <summary>
        /// Gets or Sets WebhookUrl
        /// </summary>
        [DataMember(Name = "webhook_url", EmitDefaultValue = true)]
        public string WebhookUrl { get; set; }

        /// <summary>
        /// Gets or Sets WebhookSecret
        /// </summary>
        [DataMember(Name = "webhook_secret", EmitDefaultValue = true)]
        public string WebhookSecret { get; set; }

        /// <summary>
        /// Gets or Sets FilterTypes
        /// </summary>
        [DataMember(Name = "filter_types", EmitDefaultValue = true)]
        public List<string> FilterTypes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StreamMonitorCreate {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Usernames: ").Append(Usernames).Append("\n");
            sb.Append("  WebhookUrl: ").Append(WebhookUrl).Append("\n");
            sb.Append("  WebhookSecret: ").Append(WebhookSecret).Append("\n");
            sb.Append("  FilterTypes: ").Append(FilterTypes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 100)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 100.", new [] { "Name" });
            }

            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            // WebhookUrl (string) maxLength
            if (this.WebhookUrl != null && this.WebhookUrl.Length > 2048)
            {
                yield return new ValidationResult("Invalid value for WebhookUrl, length must be less than 2048.", new [] { "WebhookUrl" });
            }

            // WebhookSecret (string) maxLength
            if (this.WebhookSecret != null && this.WebhookSecret.Length > 128)
            {
                yield return new ValidationResult("Invalid value for WebhookSecret, length must be less than 128.", new [] { "WebhookSecret" });
            }

            yield break;
        }
    }

}
