/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ScrapeBadger.Client.FileParameter;
using OpenAPIDateConverter = ScrapeBadger.Client.OpenAPIDateConverter;

namespace ScrapeBadger.Model
{
    /// <summary>
    /// Active subscription details (null when PAYG-only).
    /// </summary>
    [DataContract(Name = "SubscriptionInfo")]
    public partial class SubscriptionInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SubscriptionInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SubscriptionInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SubscriptionInfo" /> class.
        /// </summary>
        /// <param name="planCode">planCode (required).</param>
        /// <param name="planTitle">planTitle (required).</param>
        /// <param name="billingCadence">billingCadence (required).</param>
        /// <param name="status">status (required).</param>
        /// <param name="currentPeriodStart">currentPeriodStart.</param>
        /// <param name="currentPeriodEnd">currentPeriodEnd.</param>
        /// <param name="cancelAtPeriodEnd">cancelAtPeriodEnd (default to false).</param>
        /// <param name="cancelEffectiveAt">cancelEffectiveAt.</param>
        /// <param name="monthlyCredits">monthlyCredits (default to 0).</param>
        /// <param name="pendingPlanCode">pendingPlanCode.</param>
        /// <param name="pendingPlanTitle">pendingPlanTitle.</param>
        /// <param name="pendingChangeEffectiveAt">pendingChangeEffectiveAt.</param>
        public SubscriptionInfo(string planCode = default(string), string planTitle = default(string), string billingCadence = default(string), string status = default(string), DateTime? currentPeriodStart = default(DateTime?), DateTime? currentPeriodEnd = default(DateTime?), bool cancelAtPeriodEnd = false, DateTime? cancelEffectiveAt = default(DateTime?), int monthlyCredits = 0, string pendingPlanCode = default(string), string pendingPlanTitle = default(string), DateTime? pendingChangeEffectiveAt = default(DateTime?))
        {
            // to ensure "planCode" is required (not null)
            if (planCode == null)
            {
                throw new ArgumentNullException("planCode is a required property for SubscriptionInfo and cannot be null");
            }
            this.PlanCode = planCode;
            // to ensure "planTitle" is required (not null)
            if (planTitle == null)
            {
                throw new ArgumentNullException("planTitle is a required property for SubscriptionInfo and cannot be null");
            }
            this.PlanTitle = planTitle;
            // to ensure "billingCadence" is required (not null)
            if (billingCadence == null)
            {
                throw new ArgumentNullException("billingCadence is a required property for SubscriptionInfo and cannot be null");
            }
            this.BillingCadence = billingCadence;
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for SubscriptionInfo and cannot be null");
            }
            this.Status = status;
            this.CurrentPeriodStart = currentPeriodStart;
            this.CurrentPeriodEnd = currentPeriodEnd;
            this.CancelAtPeriodEnd = cancelAtPeriodEnd;
            this.CancelEffectiveAt = cancelEffectiveAt;
            this.MonthlyCredits = monthlyCredits;
            this.PendingPlanCode = pendingPlanCode;
            this.PendingPlanTitle = pendingPlanTitle;
            this.PendingChangeEffectiveAt = pendingChangeEffectiveAt;
        }

        /// <summary>
        /// Gets or Sets PlanCode
        /// </summary>
        [DataMember(Name = "plan_code", IsRequired = true, EmitDefaultValue = true)]
        public string PlanCode { get; set; }

        /// <summary>
        /// Gets or Sets PlanTitle
        /// </summary>
        [DataMember(Name = "plan_title", IsRequired = true, EmitDefaultValue = true)]
        public string PlanTitle { get; set; }

        /// <summary>
        /// Gets or Sets BillingCadence
        /// </summary>
        [DataMember(Name = "billing_cadence", IsRequired = true, EmitDefaultValue = true)]
        public string BillingCadence { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets CurrentPeriodStart
        /// </summary>
        [DataMember(Name = "current_period_start", EmitDefaultValue = true)]
        public DateTime? CurrentPeriodStart { get; set; }

        /// <summary>
        /// Gets or Sets CurrentPeriodEnd
        /// </summary>
        [DataMember(Name = "current_period_end", EmitDefaultValue = true)]
        public DateTime? CurrentPeriodEnd { get; set; }

        /// <summary>
        /// Gets or Sets CancelAtPeriodEnd
        /// </summary>
        [DataMember(Name = "cancel_at_period_end", EmitDefaultValue = true)]
        public bool CancelAtPeriodEnd { get; set; }

        /// <summary>
        /// Gets or Sets CancelEffectiveAt
        /// </summary>
        [DataMember(Name = "cancel_effective_at", EmitDefaultValue = true)]
        public DateTime? CancelEffectiveAt { get; set; }

        /// <summary>
        /// Gets or Sets MonthlyCredits
        /// </summary>
        [DataMember(Name = "monthly_credits", EmitDefaultValue = false)]
        public int MonthlyCredits { get; set; }

        /// <summary>
        /// Gets or Sets PendingPlanCode
        /// </summary>
        [DataMember(Name = "pending_plan_code", EmitDefaultValue = true)]
        public string PendingPlanCode { get; set; }

        /// <summary>
        /// Gets or Sets PendingPlanTitle
        /// </summary>
        [DataMember(Name = "pending_plan_title", EmitDefaultValue = true)]
        public string PendingPlanTitle { get; set; }

        /// <summary>
        /// Gets or Sets PendingChangeEffectiveAt
        /// </summary>
        [DataMember(Name = "pending_change_effective_at", EmitDefaultValue = true)]
        public DateTime? PendingChangeEffectiveAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SubscriptionInfo {\n");
            sb.Append("  PlanCode: ").Append(PlanCode).Append("\n");
            sb.Append("  PlanTitle: ").Append(PlanTitle).Append("\n");
            sb.Append("  BillingCadence: ").Append(BillingCadence).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CurrentPeriodStart: ").Append(CurrentPeriodStart).Append("\n");
            sb.Append("  CurrentPeriodEnd: ").Append(CurrentPeriodEnd).Append("\n");
            sb.Append("  CancelAtPeriodEnd: ").Append(CancelAtPeriodEnd).Append("\n");
            sb.Append("  CancelEffectiveAt: ").Append(CancelEffectiveAt).Append("\n");
            sb.Append("  MonthlyCredits: ").Append(MonthlyCredits).Append("\n");
            sb.Append("  PendingPlanCode: ").Append(PendingPlanCode).Append("\n");
            sb.Append("  PendingPlanTitle: ").Append(PendingPlanTitle).Append("\n");
            sb.Append("  PendingChangeEffectiveAt: ").Append(PendingChangeEffectiveAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
