/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ScrapeBadger.Client.FileParameter;
using OpenAPIDateConverter = ScrapeBadger.Client.OpenAPIDateConverter;

namespace ScrapeBadger.Model
{
    /// <summary>
    /// Search by exactly one public image URL or base64-encoded image.
    /// </summary>
    [DataContract(Name = "VintedImageSearchRequest")]
    public partial class VintedImageSearchRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VintedImageSearchRequest" /> class.
        /// </summary>
        /// <param name="imageUrl">imageUrl.</param>
        /// <param name="imageBase64">imageBase64.</param>
        /// <param name="market">Vinted market code; uk aliases gb (default to &quot;fr&quot;).</param>
        /// <param name="page">page (default to 1).</param>
        /// <param name="perPage">perPage (default to 20).</param>
        /// <param name="priceFrom">priceFrom.</param>
        /// <param name="priceTo">priceTo.</param>
        /// <param name="brandIds">brandIds.</param>
        /// <param name="catalogIds">catalogIds.</param>
        /// <param name="colorIds">colorIds.</param>
        /// <param name="sizeIds">sizeIds.</param>
        /// <param name="materialIds">materialIds.</param>
        /// <param name="statusIds">statusIds.</param>
        /// <param name="time">time.</param>
        /// <param name="searchSessionId">searchSessionId.</param>
        public VintedImageSearchRequest(string imageUrl = default(string), string imageBase64 = default(string), string market = @"fr", int page = 1, int perPage = 20, decimal? priceFrom = default(decimal?), decimal? priceTo = default(decimal?), string brandIds = default(string), string catalogIds = default(string), string colorIds = default(string), string sizeIds = default(string), string materialIds = default(string), string statusIds = default(string), int? time = default(int?), string searchSessionId = default(string))
        {
            this.ImageUrl = imageUrl;
            this.ImageBase64 = imageBase64;
            // use default value if no "market" provided
            this.Market = market ?? @"fr";
            this.Page = page;
            this.PerPage = perPage;
            this.PriceFrom = priceFrom;
            this.PriceTo = priceTo;
            this.BrandIds = brandIds;
            this.CatalogIds = catalogIds;
            this.ColorIds = colorIds;
            this.SizeIds = sizeIds;
            this.MaterialIds = materialIds;
            this.StatusIds = statusIds;
            this.Time = time;
            this.SearchSessionId = searchSessionId;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Gets or Sets ImageUrl
        /// </summary>
        [DataMember(Name = "image_url", EmitDefaultValue = true)]
        public string ImageUrl { get; set; }

        /// <summary>
        /// Gets or Sets ImageBase64
        /// </summary>
        [DataMember(Name = "image_base64", EmitDefaultValue = true)]
        public string ImageBase64 { get; set; }

        /// <summary>
        /// Vinted market code; uk aliases gb
        /// </summary>
        /// <value>Vinted market code; uk aliases gb</value>
        [DataMember(Name = "market", EmitDefaultValue = false)]
        public string Market { get; set; }

        /// <summary>
        /// Gets or Sets Page
        /// </summary>
        [DataMember(Name = "page", EmitDefaultValue = false)]
        public int Page { get; set; }

        /// <summary>
        /// Gets or Sets PerPage
        /// </summary>
        [DataMember(Name = "per_page", EmitDefaultValue = false)]
        public int PerPage { get; set; }

        /// <summary>
        /// Gets or Sets PriceFrom
        /// </summary>
        [DataMember(Name = "price_from", EmitDefaultValue = true)]
        public decimal? PriceFrom { get; set; }

        /// <summary>
        /// Gets or Sets PriceTo
        /// </summary>
        [DataMember(Name = "price_to", EmitDefaultValue = true)]
        public decimal? PriceTo { get; set; }

        /// <summary>
        /// Gets or Sets BrandIds
        /// </summary>
        [DataMember(Name = "brand_ids", EmitDefaultValue = true)]
        public string BrandIds { get; set; }

        /// <summary>
        /// Gets or Sets CatalogIds
        /// </summary>
        [DataMember(Name = "catalog_ids", EmitDefaultValue = true)]
        public string CatalogIds { get; set; }

        /// <summary>
        /// Gets or Sets ColorIds
        /// </summary>
        [DataMember(Name = "color_ids", EmitDefaultValue = true)]
        public string ColorIds { get; set; }

        /// <summary>
        /// Gets or Sets SizeIds
        /// </summary>
        [DataMember(Name = "size_ids", EmitDefaultValue = true)]
        public string SizeIds { get; set; }

        /// <summary>
        /// Gets or Sets MaterialIds
        /// </summary>
        [DataMember(Name = "material_ids", EmitDefaultValue = true)]
        public string MaterialIds { get; set; }

        /// <summary>
        /// Gets or Sets StatusIds
        /// </summary>
        [DataMember(Name = "status_ids", EmitDefaultValue = true)]
        public string StatusIds { get; set; }

        /// <summary>
        /// Gets or Sets Time
        /// </summary>
        [DataMember(Name = "time", EmitDefaultValue = true)]
        public int? Time { get; set; }

        /// <summary>
        /// Gets or Sets SearchSessionId
        /// </summary>
        [DataMember(Name = "search_session_id", EmitDefaultValue = true)]
        public string SearchSessionId { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VintedImageSearchRequest {\n");
            sb.Append("  ImageUrl: ").Append(ImageUrl).Append("\n");
            sb.Append("  ImageBase64: ").Append(ImageBase64).Append("\n");
            sb.Append("  Market: ").Append(Market).Append("\n");
            sb.Append("  Page: ").Append(Page).Append("\n");
            sb.Append("  PerPage: ").Append(PerPage).Append("\n");
            sb.Append("  PriceFrom: ").Append(PriceFrom).Append("\n");
            sb.Append("  PriceTo: ").Append(PriceTo).Append("\n");
            sb.Append("  BrandIds: ").Append(BrandIds).Append("\n");
            sb.Append("  CatalogIds: ").Append(CatalogIds).Append("\n");
            sb.Append("  ColorIds: ").Append(ColorIds).Append("\n");
            sb.Append("  SizeIds: ").Append(SizeIds).Append("\n");
            sb.Append("  MaterialIds: ").Append(MaterialIds).Append("\n");
            sb.Append("  StatusIds: ").Append(StatusIds).Append("\n");
            sb.Append("  Time: ").Append(Time).Append("\n");
            sb.Append("  SearchSessionId: ").Append(SearchSessionId).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // ImageUrl (string) maxLength
            if (this.ImageUrl != null && this.ImageUrl.Length > 4096)
            {
                yield return new ValidationResult("Invalid value for ImageUrl, length must be less than 4096.", new [] { "ImageUrl" });
            }

            // ImageBase64 (string) maxLength
            if (this.ImageBase64 != null && this.ImageBase64.Length > 7100000)
            {
                yield return new ValidationResult("Invalid value for ImageBase64, length must be less than 7100000.", new [] { "ImageBase64" });
            }

            // Page (int) minimum
            if (this.Page < (int)1)
            {
                yield return new ValidationResult("Invalid value for Page, must be a value greater than or equal to 1.", new [] { "Page" });
            }

            // PerPage (int) maximum
            if (this.PerPage > (int)96)
            {
                yield return new ValidationResult("Invalid value for PerPage, must be a value less than or equal to 96.", new [] { "PerPage" });
            }

            // PerPage (int) minimum
            if (this.PerPage < (int)1)
            {
                yield return new ValidationResult("Invalid value for PerPage, must be a value greater than or equal to 1.", new [] { "PerPage" });
            }

            // PriceFrom (decimal?) minimum
            if (this.PriceFrom < (decimal?)0.0)
            {
                yield return new ValidationResult("Invalid value for PriceFrom, must be a value greater than or equal to 0.0.", new [] { "PriceFrom" });
            }

            // PriceTo (decimal?) minimum
            if (this.PriceTo < (decimal?)0.0)
            {
                yield return new ValidationResult("Invalid value for PriceTo, must be a value greater than or equal to 0.0.", new [] { "PriceTo" });
            }

            // BrandIds (string) maxLength
            if (this.BrandIds != null && this.BrandIds.Length > 1000)
            {
                yield return new ValidationResult("Invalid value for BrandIds, length must be less than 1000.", new [] { "BrandIds" });
            }

            if (this.BrandIds != null) {
                // BrandIds (string) pattern
                Regex regexBrandIds = new Regex(@"^[1-9][0-9]*(,[1-9][0-9]*)*$", RegexOptions.CultureInvariant);
                if (!regexBrandIds.Match(this.BrandIds).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for BrandIds, must match a pattern of " + regexBrandIds, new [] { "BrandIds" });
                }
            }

            // CatalogIds (string) maxLength
            if (this.CatalogIds != null && this.CatalogIds.Length > 1000)
            {
                yield return new ValidationResult("Invalid value for CatalogIds, length must be less than 1000.", new [] { "CatalogIds" });
            }

            if (this.CatalogIds != null) {
                // CatalogIds (string) pattern
                Regex regexCatalogIds = new Regex(@"^[1-9][0-9]*(,[1-9][0-9]*)*$", RegexOptions.CultureInvariant);
                if (!regexCatalogIds.Match(this.CatalogIds).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CatalogIds, must match a pattern of " + regexCatalogIds, new [] { "CatalogIds" });
                }
            }

            // ColorIds (string) maxLength
            if (this.ColorIds != null && this.ColorIds.Length > 1000)
            {
                yield return new ValidationResult("Invalid value for ColorIds, length must be less than 1000.", new [] { "ColorIds" });
            }

            if (this.ColorIds != null) {
                // ColorIds (string) pattern
                Regex regexColorIds = new Regex(@"^[1-9][0-9]*(,[1-9][0-9]*)*$", RegexOptions.CultureInvariant);
                if (!regexColorIds.Match(this.ColorIds).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ColorIds, must match a pattern of " + regexColorIds, new [] { "ColorIds" });
                }
            }

            // SizeIds (string) maxLength
            if (this.SizeIds != null && this.SizeIds.Length > 1000)
            {
                yield return new ValidationResult("Invalid value for SizeIds, length must be less than 1000.", new [] { "SizeIds" });
            }

            if (this.SizeIds != null) {
                // SizeIds (string) pattern
                Regex regexSizeIds = new Regex(@"^[1-9][0-9]*(,[1-9][0-9]*)*$", RegexOptions.CultureInvariant);
                if (!regexSizeIds.Match(this.SizeIds).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SizeIds, must match a pattern of " + regexSizeIds, new [] { "SizeIds" });
                }
            }

            // MaterialIds (string) maxLength
            if (this.MaterialIds != null && this.MaterialIds.Length > 1000)
            {
                yield return new ValidationResult("Invalid value for MaterialIds, length must be less than 1000.", new [] { "MaterialIds" });
            }

            if (this.MaterialIds != null) {
                // MaterialIds (string) pattern
                Regex regexMaterialIds = new Regex(@"^[1-9][0-9]*(,[1-9][0-9]*)*$", RegexOptions.CultureInvariant);
                if (!regexMaterialIds.Match(this.MaterialIds).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MaterialIds, must match a pattern of " + regexMaterialIds, new [] { "MaterialIds" });
                }
            }

            // StatusIds (string) maxLength
            if (this.StatusIds != null && this.StatusIds.Length > 1000)
            {
                yield return new ValidationResult("Invalid value for StatusIds, length must be less than 1000.", new [] { "StatusIds" });
            }

            if (this.StatusIds != null) {
                // StatusIds (string) pattern
                Regex regexStatusIds = new Regex(@"^[1-9][0-9]*(,[1-9][0-9]*)*$", RegexOptions.CultureInvariant);
                if (!regexStatusIds.Match(this.StatusIds).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for StatusIds, must match a pattern of " + regexStatusIds, new [] { "StatusIds" });
                }
            }

            // Time (int?) minimum
            if (this.Time < (int?)0)
            {
                yield return new ValidationResult("Invalid value for Time, must be a value greater than or equal to 0.", new [] { "Time" });
            }

            // SearchSessionId (string) maxLength
            if (this.SearchSessionId != null && this.SearchSessionId.Length > 100)
            {
                yield return new ValidationResult("Invalid value for SearchSessionId, length must be less than 100.", new [] { "SearchSessionId" });
            }

            yield break;
        }
    }

}
