/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ScrapeBadger.Client.FileParameter;
using OpenAPIDateConverter = ScrapeBadger.Client.OpenAPIDateConverter;

namespace ScrapeBadger.Model
{
    /// <summary>
    /// Parameters are validated against the discoverable operation catalog.
    /// </summary>
    [DataContract(Name = "VintedMobileReadRequest")]
    public partial class VintedMobileReadRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VintedMobileReadRequest" /> class.
        /// </summary>
        /// <param name="market">Vinted market code; uk aliases gb (default to &quot;fr&quot;).</param>
        /// <param name="parameters">Operation-specific parameters. GET /v1/vinted/mobile/operations lists types, required fields and examples..</param>
        public VintedMobileReadRequest(string market = @"fr", Dictionary<string, Object> parameters = default(Dictionary<string, Object>))
        {
            // use default value if no "market" provided
            this.Market = market ?? @"fr";
            this.Parameters = parameters;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Vinted market code; uk aliases gb
        /// </summary>
        /// <value>Vinted market code; uk aliases gb</value>
        [DataMember(Name = "market", EmitDefaultValue = false)]
        public string Market { get; set; }

        /// <summary>
        /// Operation-specific parameters. GET /v1/vinted/mobile/operations lists types, required fields and examples.
        /// </summary>
        /// <value>Operation-specific parameters. GET /v1/vinted/mobile/operations lists types, required fields and examples.</value>
        [DataMember(Name = "parameters", EmitDefaultValue = false)]
        public Dictionary<string, Object> Parameters { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VintedMobileReadRequest {\n");
            sb.Append("  Market: ").Append(Market).Append("\n");
            sb.Append("  Parameters: ").Append(Parameters).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
