/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ScrapeBadger.Client.FileParameter;
using OpenAPIDateConverter = ScrapeBadger.Client.OpenAPIDateConverter;

namespace ScrapeBadger.Model
{
    /// <summary>
    /// Configure webhook on a monitor.
    /// </summary>
    [DataContract(Name = "WebhookCreate")]
    public partial class WebhookCreate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WebhookCreate" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WebhookCreate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WebhookCreate" /> class.
        /// </summary>
        /// <param name="monitorId">monitorId (required).</param>
        /// <param name="url">url (required).</param>
        /// <param name="secret">secret.</param>
        public WebhookCreate(string monitorId = default(string), string url = default(string), string secret = default(string))
        {
            // to ensure "monitorId" is required (not null)
            if (monitorId == null)
            {
                throw new ArgumentNullException("monitorId is a required property for WebhookCreate and cannot be null");
            }
            this.MonitorId = monitorId;
            // to ensure "url" is required (not null)
            if (url == null)
            {
                throw new ArgumentNullException("url is a required property for WebhookCreate and cannot be null");
            }
            this.Url = url;
            this.Secret = secret;
        }

        /// <summary>
        /// Gets or Sets MonitorId
        /// </summary>
        [DataMember(Name = "monitor_id", IsRequired = true, EmitDefaultValue = true)]
        public string MonitorId { get; set; }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [DataMember(Name = "url", IsRequired = true, EmitDefaultValue = true)]
        public string Url { get; set; }

        /// <summary>
        /// Gets or Sets Secret
        /// </summary>
        [DataMember(Name = "secret", EmitDefaultValue = true)]
        public string Secret { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WebhookCreate {\n");
            sb.Append("  MonitorId: ").Append(MonitorId).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Secret: ").Append(Secret).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Url (string) maxLength
            if (this.Url != null && this.Url.Length > 2048)
            {
                yield return new ValidationResult("Invalid value for Url, length must be less than 2048.", new [] { "Url" });
            }

            // Secret (string) maxLength
            if (this.Secret != null && this.Secret.Length > 128)
            {
                yield return new ValidationResult("Invalid value for Secret, length must be less than 128.", new [] { "Secret" });
            }

            yield break;
        }
    }

}
