/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ScrapeBadger.Client.FileParameter;
using OpenAPIDateConverter = ScrapeBadger.Client.OpenAPIDateConverter;

namespace ScrapeBadger.Model
{
    /// <summary>
    /// Test webhook delivery result.
    /// </summary>
    [DataContract(Name = "WebhookTestResponse")]
    public partial class WebhookTestResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WebhookTestResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WebhookTestResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WebhookTestResponse" /> class.
        /// </summary>
        /// <param name="success">success (required).</param>
        /// <param name="statusCode">statusCode.</param>
        /// <param name="responseTimeMs">Round-trip time in milliseconds (required).</param>
        /// <param name="error">error.</param>
        public WebhookTestResponse(bool success = default(bool), int? statusCode = default(int?), decimal responseTimeMs = default(decimal), string error = default(string))
        {
            this.Success = success;
            this.ResponseTimeMs = responseTimeMs;
            this.StatusCode = statusCode;
            this.Error = error;
        }

        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        [DataMember(Name = "success", IsRequired = true, EmitDefaultValue = true)]
        public bool Success { get; set; }

        /// <summary>
        /// Gets or Sets StatusCode
        /// </summary>
        [DataMember(Name = "status_code", EmitDefaultValue = true)]
        public int? StatusCode { get; set; }

        /// <summary>
        /// Round-trip time in milliseconds
        /// </summary>
        /// <value>Round-trip time in milliseconds</value>
        [DataMember(Name = "response_time_ms", IsRequired = true, EmitDefaultValue = true)]
        public decimal ResponseTimeMs { get; set; }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [DataMember(Name = "error", EmitDefaultValue = true)]
        public string Error { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WebhookTestResponse {\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  StatusCode: ").Append(StatusCode).Append("\n");
            sb.Append("  ResponseTimeMs: ").Append(ResponseTimeMs).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
