/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using ScrapeBadger.Client;
using ScrapeBadger.Model;

namespace ScrapeBadger.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IApartmentsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Apartments scraper health check
        /// </summary>
        /// <remarks>
        /// Check health of the Apartments scraper service (accepts HEAD for UptimeRobot).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Object</returns>
        Object ApartmentsApartmentsScraperHealthCheck();

        /// <summary>
        /// Apartments scraper health check
        /// </summary>
        /// <remarks>
        /// Check health of the Apartments scraper service (accepts HEAD for UptimeRobot).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> ApartmentsApartmentsScraperHealthCheckWithHttpInfo();
        /// <summary>
        /// Apartments scraper health check
        /// </summary>
        /// <remarks>
        /// Check health of the Apartments scraper service (accepts HEAD for UptimeRobot).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Object</returns>
        Object ApartmentsApartmentsScraperHealthCheckHead();

        /// <summary>
        /// Apartments scraper health check
        /// </summary>
        /// <remarks>
        /// Check health of the Apartments scraper service (accepts HEAD for UptimeRobot).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> ApartmentsApartmentsScraperHealthCheckHeadWithHttpInfo();
        /// <summary>
        /// Get property detail by slug + id
        /// </summary>
        /// <remarks>
        /// Get a property by its SEO slug and 7-character listing id.
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slug"></param>
        /// <param name="propertyId"></param>
        /// <returns>Object</returns>
        Object ApartmentsGetPropertyDetailBySlugId(string slug, string propertyId);

        /// <summary>
        /// Get property detail by slug + id
        /// </summary>
        /// <remarks>
        /// Get a property by its SEO slug and 7-character listing id.
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slug"></param>
        /// <param name="propertyId"></param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> ApartmentsGetPropertyDetailBySlugIdWithHttpInfo(string slug, string propertyId);
        /// <summary>
        /// Get property detail by URL
        /// </summary>
        /// <remarks>
        /// Get an apartments.com property with full per-unit pricing and availability.
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="url">Full apartments.com property URL, e.g. https://www.apartments.com/urbane-kansas-city-mo/wcd6e5k/</param>
        /// <returns>Object</returns>
        Object ApartmentsGetPropertyDetailByUrl(string url);

        /// <summary>
        /// Get property detail by URL
        /// </summary>
        /// <remarks>
        /// Get an apartments.com property with full per-unit pricing and availability.
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="url">Full apartments.com property URL, e.g. https://www.apartments.com/urbane-kansas-city-mo/wcd6e5k/</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> ApartmentsGetPropertyDetailByUrlWithHttpInfo(string url);
        /// <summary>
        /// Search rental listings
        /// </summary>
        /// <remarks>
        /// Search apartments.com for rental properties. 40 cards per page.
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="location">apartments.com location slug, e.g. &#39;kansas-city-mo&#39;</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="beds">0&#x3D;studio, 1-4 bedrooms (optional)</param>
        /// <param name="minPrice"> (optional)</param>
        /// <param name="maxPrice"> (optional)</param>
        /// <returns>Object</returns>
        Object ApartmentsSearchRentalListings(string location, int? page = default(int?), int? beds = default(int?), int? minPrice = default(int?), int? maxPrice = default(int?));

        /// <summary>
        /// Search rental listings
        /// </summary>
        /// <remarks>
        /// Search apartments.com for rental properties. 40 cards per page.
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="location">apartments.com location slug, e.g. &#39;kansas-city-mo&#39;</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="beds">0&#x3D;studio, 1-4 bedrooms (optional)</param>
        /// <param name="minPrice"> (optional)</param>
        /// <param name="maxPrice"> (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> ApartmentsSearchRentalListingsWithHttpInfo(string location, int? page = default(int?), int? beds = default(int?), int? minPrice = default(int?), int? maxPrice = default(int?));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IApartmentsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Apartments scraper health check
        /// </summary>
        /// <remarks>
        /// Check health of the Apartments scraper service (accepts HEAD for UptimeRobot).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> ApartmentsApartmentsScraperHealthCheckAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Apartments scraper health check
        /// </summary>
        /// <remarks>
        /// Check health of the Apartments scraper service (accepts HEAD for UptimeRobot).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApartmentsApartmentsScraperHealthCheckWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Apartments scraper health check
        /// </summary>
        /// <remarks>
        /// Check health of the Apartments scraper service (accepts HEAD for UptimeRobot).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> ApartmentsApartmentsScraperHealthCheckHeadAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Apartments scraper health check
        /// </summary>
        /// <remarks>
        /// Check health of the Apartments scraper service (accepts HEAD for UptimeRobot).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApartmentsApartmentsScraperHealthCheckHeadWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Get property detail by slug + id
        /// </summary>
        /// <remarks>
        /// Get a property by its SEO slug and 7-character listing id.
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slug"></param>
        /// <param name="propertyId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> ApartmentsGetPropertyDetailBySlugIdAsync(string slug, string propertyId, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Get property detail by slug + id
        /// </summary>
        /// <remarks>
        /// Get a property by its SEO slug and 7-character listing id.
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slug"></param>
        /// <param name="propertyId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApartmentsGetPropertyDetailBySlugIdWithHttpInfoAsync(string slug, string propertyId, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Get property detail by URL
        /// </summary>
        /// <remarks>
        /// Get an apartments.com property with full per-unit pricing and availability.
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="url">Full apartments.com property URL, e.g. https://www.apartments.com/urbane-kansas-city-mo/wcd6e5k/</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> ApartmentsGetPropertyDetailByUrlAsync(string url, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Get property detail by URL
        /// </summary>
        /// <remarks>
        /// Get an apartments.com property with full per-unit pricing and availability.
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="url">Full apartments.com property URL, e.g. https://www.apartments.com/urbane-kansas-city-mo/wcd6e5k/</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApartmentsGetPropertyDetailByUrlWithHttpInfoAsync(string url, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Search rental listings
        /// </summary>
        /// <remarks>
        /// Search apartments.com for rental properties. 40 cards per page.
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="location">apartments.com location slug, e.g. &#39;kansas-city-mo&#39;</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="beds">0&#x3D;studio, 1-4 bedrooms (optional)</param>
        /// <param name="minPrice"> (optional)</param>
        /// <param name="maxPrice"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> ApartmentsSearchRentalListingsAsync(string location, int? page = default(int?), int? beds = default(int?), int? minPrice = default(int?), int? maxPrice = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Search rental listings
        /// </summary>
        /// <remarks>
        /// Search apartments.com for rental properties. 40 cards per page.
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="location">apartments.com location slug, e.g. &#39;kansas-city-mo&#39;</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="beds">0&#x3D;studio, 1-4 bedrooms (optional)</param>
        /// <param name="minPrice"> (optional)</param>
        /// <param name="maxPrice"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApartmentsSearchRentalListingsWithHttpInfoAsync(string location, int? page = default(int?), int? beds = default(int?), int? minPrice = default(int?), int? maxPrice = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IApartmentsApi : IApartmentsApiSync, IApartmentsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ApartmentsApi : IDisposable, IApartmentsApi
    {
        private ScrapeBadger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ApartmentsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public ApartmentsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ApartmentsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public ApartmentsApi(string basePath)
        {
            this.Configuration = ScrapeBadger.Client.Configuration.MergeConfigurations(
                ScrapeBadger.Client.GlobalConfiguration.Instance,
                new ScrapeBadger.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new ScrapeBadger.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = ScrapeBadger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ApartmentsApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public ApartmentsApi(ScrapeBadger.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = ScrapeBadger.Client.Configuration.MergeConfigurations(
                ScrapeBadger.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new ScrapeBadger.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = ScrapeBadger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ApartmentsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ApartmentsApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ApartmentsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ApartmentsApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = ScrapeBadger.Client.Configuration.MergeConfigurations(
                ScrapeBadger.Client.GlobalConfiguration.Instance,
                new ScrapeBadger.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new ScrapeBadger.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = ScrapeBadger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ApartmentsApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ApartmentsApi(HttpClient client, ScrapeBadger.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = ScrapeBadger.Client.Configuration.MergeConfigurations(
                ScrapeBadger.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new ScrapeBadger.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = ScrapeBadger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ApartmentsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public ApartmentsApi(ScrapeBadger.Client.ISynchronousClient client, ScrapeBadger.Client.IAsynchronousClient asyncClient, ScrapeBadger.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = ScrapeBadger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public ScrapeBadger.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public ScrapeBadger.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public ScrapeBadger.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public ScrapeBadger.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ScrapeBadger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Apartments scraper health check Check health of the Apartments scraper service (accepts HEAD for UptimeRobot).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Object</returns>
        public Object ApartmentsApartmentsScraperHealthCheck()
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = ApartmentsApartmentsScraperHealthCheckWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Apartments scraper health check Check health of the Apartments scraper service (accepts HEAD for UptimeRobot).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object</returns>
        public ScrapeBadger.Client.ApiResponse<Object> ApartmentsApartmentsScraperHealthCheckWithHttpInfo()
        {
            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/v1/apartments/health", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApartmentsApartmentsScraperHealthCheck", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Apartments scraper health check Check health of the Apartments scraper service (accepts HEAD for UptimeRobot).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> ApartmentsApartmentsScraperHealthCheckAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = await ApartmentsApartmentsScraperHealthCheckWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Apartments scraper health check Check health of the Apartments scraper service (accepts HEAD for UptimeRobot).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ScrapeBadger.Client.ApiResponse<Object>> ApartmentsApartmentsScraperHealthCheckWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/v1/apartments/health", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApartmentsApartmentsScraperHealthCheck", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Apartments scraper health check Check health of the Apartments scraper service (accepts HEAD for UptimeRobot).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Object</returns>
        public Object ApartmentsApartmentsScraperHealthCheckHead()
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = ApartmentsApartmentsScraperHealthCheckHeadWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Apartments scraper health check Check health of the Apartments scraper service (accepts HEAD for UptimeRobot).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object</returns>
        public ScrapeBadger.Client.ApiResponse<Object> ApartmentsApartmentsScraperHealthCheckHeadWithHttpInfo()
        {
            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Head<Object>("/v1/apartments/health", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApartmentsApartmentsScraperHealthCheckHead", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Apartments scraper health check Check health of the Apartments scraper service (accepts HEAD for UptimeRobot).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> ApartmentsApartmentsScraperHealthCheckHeadAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = await ApartmentsApartmentsScraperHealthCheckHeadWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Apartments scraper health check Check health of the Apartments scraper service (accepts HEAD for UptimeRobot).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ScrapeBadger.Client.ApiResponse<Object>> ApartmentsApartmentsScraperHealthCheckHeadWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.HeadAsync<Object>("/v1/apartments/health", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApartmentsApartmentsScraperHealthCheckHead", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get property detail by slug + id Get a property by its SEO slug and 7-character listing id.
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slug"></param>
        /// <param name="propertyId"></param>
        /// <returns>Object</returns>
        public Object ApartmentsGetPropertyDetailBySlugId(string slug, string propertyId)
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = ApartmentsGetPropertyDetailBySlugIdWithHttpInfo(slug, propertyId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get property detail by slug + id Get a property by its SEO slug and 7-character listing id.
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slug"></param>
        /// <param name="propertyId"></param>
        /// <returns>ApiResponse of Object</returns>
        public ScrapeBadger.Client.ApiResponse<Object> ApartmentsGetPropertyDetailBySlugIdWithHttpInfo(string slug, string propertyId)
        {
            // verify the required parameter 'slug' is set
            if (slug == null)
                throw new ScrapeBadger.Client.ApiException(400, "Missing required parameter 'slug' when calling ApartmentsApi->ApartmentsGetPropertyDetailBySlugId");

            // verify the required parameter 'propertyId' is set
            if (propertyId == null)
                throw new ScrapeBadger.Client.ApiException(400, "Missing required parameter 'propertyId' when calling ApartmentsApi->ApartmentsGetPropertyDetailBySlugId");

            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("slug", ScrapeBadger.Client.ClientUtils.ParameterToString(slug)); // path parameter
            localVarRequestOptions.PathParameters.Add("property_id", ScrapeBadger.Client.ClientUtils.ParameterToString(propertyId)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/v1/apartments/properties/{slug}/{property_id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApartmentsGetPropertyDetailBySlugId", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get property detail by slug + id Get a property by its SEO slug and 7-character listing id.
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slug"></param>
        /// <param name="propertyId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> ApartmentsGetPropertyDetailBySlugIdAsync(string slug, string propertyId, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = await ApartmentsGetPropertyDetailBySlugIdWithHttpInfoAsync(slug, propertyId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get property detail by slug + id Get a property by its SEO slug and 7-character listing id.
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slug"></param>
        /// <param name="propertyId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ScrapeBadger.Client.ApiResponse<Object>> ApartmentsGetPropertyDetailBySlugIdWithHttpInfoAsync(string slug, string propertyId, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'slug' is set
            if (slug == null)
                throw new ScrapeBadger.Client.ApiException(400, "Missing required parameter 'slug' when calling ApartmentsApi->ApartmentsGetPropertyDetailBySlugId");

            // verify the required parameter 'propertyId' is set
            if (propertyId == null)
                throw new ScrapeBadger.Client.ApiException(400, "Missing required parameter 'propertyId' when calling ApartmentsApi->ApartmentsGetPropertyDetailBySlugId");


            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("slug", ScrapeBadger.Client.ClientUtils.ParameterToString(slug)); // path parameter
            localVarRequestOptions.PathParameters.Add("property_id", ScrapeBadger.Client.ClientUtils.ParameterToString(propertyId)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/v1/apartments/properties/{slug}/{property_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApartmentsGetPropertyDetailBySlugId", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get property detail by URL Get an apartments.com property with full per-unit pricing and availability.
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="url">Full apartments.com property URL, e.g. https://www.apartments.com/urbane-kansas-city-mo/wcd6e5k/</param>
        /// <returns>Object</returns>
        public Object ApartmentsGetPropertyDetailByUrl(string url)
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = ApartmentsGetPropertyDetailByUrlWithHttpInfo(url);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get property detail by URL Get an apartments.com property with full per-unit pricing and availability.
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="url">Full apartments.com property URL, e.g. https://www.apartments.com/urbane-kansas-city-mo/wcd6e5k/</param>
        /// <returns>ApiResponse of Object</returns>
        public ScrapeBadger.Client.ApiResponse<Object> ApartmentsGetPropertyDetailByUrlWithHttpInfo(string url)
        {
            // verify the required parameter 'url' is set
            if (url == null)
                throw new ScrapeBadger.Client.ApiException(400, "Missing required parameter 'url' when calling ApartmentsApi->ApartmentsGetPropertyDetailByUrl");

            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "url", url));

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/v1/apartments/property", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApartmentsGetPropertyDetailByUrl", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get property detail by URL Get an apartments.com property with full per-unit pricing and availability.
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="url">Full apartments.com property URL, e.g. https://www.apartments.com/urbane-kansas-city-mo/wcd6e5k/</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> ApartmentsGetPropertyDetailByUrlAsync(string url, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = await ApartmentsGetPropertyDetailByUrlWithHttpInfoAsync(url, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get property detail by URL Get an apartments.com property with full per-unit pricing and availability.
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="url">Full apartments.com property URL, e.g. https://www.apartments.com/urbane-kansas-city-mo/wcd6e5k/</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ScrapeBadger.Client.ApiResponse<Object>> ApartmentsGetPropertyDetailByUrlWithHttpInfoAsync(string url, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'url' is set
            if (url == null)
                throw new ScrapeBadger.Client.ApiException(400, "Missing required parameter 'url' when calling ApartmentsApi->ApartmentsGetPropertyDetailByUrl");


            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "url", url));

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/v1/apartments/property", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApartmentsGetPropertyDetailByUrl", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Search rental listings Search apartments.com for rental properties. 40 cards per page.
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="location">apartments.com location slug, e.g. &#39;kansas-city-mo&#39;</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="beds">0&#x3D;studio, 1-4 bedrooms (optional)</param>
        /// <param name="minPrice"> (optional)</param>
        /// <param name="maxPrice"> (optional)</param>
        /// <returns>Object</returns>
        public Object ApartmentsSearchRentalListings(string location, int? page = default(int?), int? beds = default(int?), int? minPrice = default(int?), int? maxPrice = default(int?))
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = ApartmentsSearchRentalListingsWithHttpInfo(location, page, beds, minPrice, maxPrice);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Search rental listings Search apartments.com for rental properties. 40 cards per page.
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="location">apartments.com location slug, e.g. &#39;kansas-city-mo&#39;</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="beds">0&#x3D;studio, 1-4 bedrooms (optional)</param>
        /// <param name="minPrice"> (optional)</param>
        /// <param name="maxPrice"> (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        public ScrapeBadger.Client.ApiResponse<Object> ApartmentsSearchRentalListingsWithHttpInfo(string location, int? page = default(int?), int? beds = default(int?), int? minPrice = default(int?), int? maxPrice = default(int?))
        {
            // verify the required parameter 'location' is set
            if (location == null)
                throw new ScrapeBadger.Client.ApiException(400, "Missing required parameter 'location' when calling ApartmentsApi->ApartmentsSearchRentalListings");

            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "location", location));
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (beds != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "beds", beds));
            }
            if (minPrice != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "min_price", minPrice));
            }
            if (maxPrice != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "max_price", maxPrice));
            }

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/v1/apartments/search", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApartmentsSearchRentalListings", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Search rental listings Search apartments.com for rental properties. 40 cards per page.
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="location">apartments.com location slug, e.g. &#39;kansas-city-mo&#39;</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="beds">0&#x3D;studio, 1-4 bedrooms (optional)</param>
        /// <param name="minPrice"> (optional)</param>
        /// <param name="maxPrice"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> ApartmentsSearchRentalListingsAsync(string location, int? page = default(int?), int? beds = default(int?), int? minPrice = default(int?), int? maxPrice = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = await ApartmentsSearchRentalListingsWithHttpInfoAsync(location, page, beds, minPrice, maxPrice, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Search rental listings Search apartments.com for rental properties. 40 cards per page.
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="location">apartments.com location slug, e.g. &#39;kansas-city-mo&#39;</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="beds">0&#x3D;studio, 1-4 bedrooms (optional)</param>
        /// <param name="minPrice"> (optional)</param>
        /// <param name="maxPrice"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ScrapeBadger.Client.ApiResponse<Object>> ApartmentsSearchRentalListingsWithHttpInfoAsync(string location, int? page = default(int?), int? beds = default(int?), int? minPrice = default(int?), int? maxPrice = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'location' is set
            if (location == null)
                throw new ScrapeBadger.Client.ApiException(400, "Missing required parameter 'location' when calling ApartmentsApi->ApartmentsSearchRentalListings");


            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "location", location));
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (beds != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "beds", beds));
            }
            if (minPrice != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "min_price", minPrice));
            }
            if (maxPrice != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "max_price", maxPrice));
            }

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/v1/apartments/search", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApartmentsSearchRentalListings", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
