/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using ScrapeBadger.Client;
using ScrapeBadger.Model;

namespace ScrapeBadger.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDepopApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Depop scraper health check
        /// </summary>
        /// <remarks>
        /// Check health of the Depop scraper service (accepts HEAD).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Object</returns>
        Object DepopDepopScraperHealthCheck();

        /// <summary>
        /// Depop scraper health check
        /// </summary>
        /// <remarks>
        /// Check health of the Depop scraper service (accepts HEAD).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> DepopDepopScraperHealthCheckWithHttpInfo();
        /// <summary>
        /// Depop scraper health check
        /// </summary>
        /// <remarks>
        /// Check health of the Depop scraper service (accepts HEAD).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Object</returns>
        Object DepopDepopScraperHealthCheckHead();

        /// <summary>
        /// Depop scraper health check
        /// </summary>
        /// <remarks>
        /// Check health of the Depop scraper service (accepts HEAD).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> DepopDepopScraperHealthCheckHeadWithHttpInfo();
        /// <summary>
        /// Get a user&#39;s products
        /// </summary>
        /// <remarks>
        /// A user&#39;s active listings (cursor-paginated).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username"></param>
        /// <param name="market">Market code (optional, default to &quot;us&quot;)</param>
        /// <param name="perPage"> (optional, default to 24)</param>
        /// <param name="cursor">Pagination cursor (optional)</param>
        /// <returns>Object</returns>
        Object DepopGetAUserSProducts(string username, string market = default(string), int? perPage = default(int?), string cursor = default(string));

        /// <summary>
        /// Get a user&#39;s products
        /// </summary>
        /// <remarks>
        /// A user&#39;s active listings (cursor-paginated).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username"></param>
        /// <param name="market">Market code (optional, default to &quot;us&quot;)</param>
        /// <param name="perPage"> (optional, default to 24)</param>
        /// <param name="cursor">Pagination cursor (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> DepopGetAUserSProductsWithHttpInfo(string username, string market = default(string), int? perPage = default(int?), string cursor = default(string));
        /// <summary>
        /// Get product detail
        /// </summary>
        /// <remarks>
        /// Full detail for a single product (by numeric id or slug).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId"></param>
        /// <param name="market">Market code (optional, default to &quot;us&quot;)</param>
        /// <returns>Object</returns>
        Object DepopGetProductDetail(string productId, string market = default(string));

        /// <summary>
        /// Get product detail
        /// </summary>
        /// <remarks>
        /// Full detail for a single product (by numeric id or slug).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId"></param>
        /// <param name="market">Market code (optional, default to &quot;us&quot;)</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> DepopGetProductDetailWithHttpInfo(string productId, string market = default(string));
        /// <summary>
        /// Get shop/user profile
        /// </summary>
        /// <remarks>
        /// Public shop/user profile by username.
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username"></param>
        /// <param name="market">Market code (optional, default to &quot;us&quot;)</param>
        /// <returns>Object</returns>
        Object DepopGetShopUserProfile(string username, string market = default(string));

        /// <summary>
        /// Get shop/user profile
        /// </summary>
        /// <remarks>
        /// Public shop/user profile by username.
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username"></param>
        /// <param name="market">Market code (optional, default to &quot;us&quot;)</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> DepopGetShopUserProfileWithHttpInfo(string username, string market = default(string));
        /// <summary>
        /// List markets
        /// </summary>
        /// <remarks>
        /// List supported Depop markets (country + currency).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Object</returns>
        Object DepopListMarkets();

        /// <summary>
        /// List markets
        /// </summary>
        /// <remarks>
        /// List supported Depop markets (country + currency).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> DepopListMarketsWithHttpInfo();
        /// <summary>
        /// Search Depop products
        /// </summary>
        /// <remarks>
        /// Search the Depop catalog with filters (cursor-paginated).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search text, e.g. &#39;nike vintage&#39;</param>
        /// <param name="market">Market code (us, gb, au, it, fr, ...) (optional, default to &quot;us&quot;)</param>
        /// <param name="perPage">Results per page (optional, default to 24)</param>
        /// <param name="cursor">Pagination cursor (from previous page) (optional)</param>
        /// <param name="priceMin">Minimum price (optional)</param>
        /// <param name="priceMax">Maximum price (optional)</param>
        /// <param name="brands">Comma-separated brand IDs (optional)</param>
        /// <param name="categories">Comma-separated category IDs (optional)</param>
        /// <param name="sizes">Comma-separated size IDs (optional)</param>
        /// <param name="conditions">Comma-separated condition slugs (brand_new, used_excellent, ...) (optional)</param>
        /// <param name="gender">male | female (optional)</param>
        /// <param name="sort">relevance | newlyListed | priceAscending | priceDescending (optional)</param>
        /// <returns>Object</returns>
        Object DepopSearchDepopProducts(string query, string market = default(string), int? perPage = default(int?), string cursor = default(string), decimal? priceMin = default(decimal?), decimal? priceMax = default(decimal?), string brands = default(string), string categories = default(string), string sizes = default(string), string conditions = default(string), string gender = default(string), string sort = default(string));

        /// <summary>
        /// Search Depop products
        /// </summary>
        /// <remarks>
        /// Search the Depop catalog with filters (cursor-paginated).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search text, e.g. &#39;nike vintage&#39;</param>
        /// <param name="market">Market code (us, gb, au, it, fr, ...) (optional, default to &quot;us&quot;)</param>
        /// <param name="perPage">Results per page (optional, default to 24)</param>
        /// <param name="cursor">Pagination cursor (from previous page) (optional)</param>
        /// <param name="priceMin">Minimum price (optional)</param>
        /// <param name="priceMax">Maximum price (optional)</param>
        /// <param name="brands">Comma-separated brand IDs (optional)</param>
        /// <param name="categories">Comma-separated category IDs (optional)</param>
        /// <param name="sizes">Comma-separated size IDs (optional)</param>
        /// <param name="conditions">Comma-separated condition slugs (brand_new, used_excellent, ...) (optional)</param>
        /// <param name="gender">male | female (optional)</param>
        /// <param name="sort">relevance | newlyListed | priceAscending | priceDescending (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> DepopSearchDepopProductsWithHttpInfo(string query, string market = default(string), int? perPage = default(int?), string cursor = default(string), decimal? priceMin = default(decimal?), decimal? priceMax = default(decimal?), string brands = default(string), string categories = default(string), string sizes = default(string), string conditions = default(string), string gender = default(string), string sort = default(string));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDepopApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Depop scraper health check
        /// </summary>
        /// <remarks>
        /// Check health of the Depop scraper service (accepts HEAD).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> DepopDepopScraperHealthCheckAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Depop scraper health check
        /// </summary>
        /// <remarks>
        /// Check health of the Depop scraper service (accepts HEAD).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DepopDepopScraperHealthCheckWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Depop scraper health check
        /// </summary>
        /// <remarks>
        /// Check health of the Depop scraper service (accepts HEAD).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> DepopDepopScraperHealthCheckHeadAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Depop scraper health check
        /// </summary>
        /// <remarks>
        /// Check health of the Depop scraper service (accepts HEAD).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DepopDepopScraperHealthCheckHeadWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Get a user&#39;s products
        /// </summary>
        /// <remarks>
        /// A user&#39;s active listings (cursor-paginated).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username"></param>
        /// <param name="market">Market code (optional, default to &quot;us&quot;)</param>
        /// <param name="perPage"> (optional, default to 24)</param>
        /// <param name="cursor">Pagination cursor (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> DepopGetAUserSProductsAsync(string username, string market = default(string), int? perPage = default(int?), string cursor = default(string), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Get a user&#39;s products
        /// </summary>
        /// <remarks>
        /// A user&#39;s active listings (cursor-paginated).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username"></param>
        /// <param name="market">Market code (optional, default to &quot;us&quot;)</param>
        /// <param name="perPage"> (optional, default to 24)</param>
        /// <param name="cursor">Pagination cursor (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DepopGetAUserSProductsWithHttpInfoAsync(string username, string market = default(string), int? perPage = default(int?), string cursor = default(string), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Get product detail
        /// </summary>
        /// <remarks>
        /// Full detail for a single product (by numeric id or slug).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId"></param>
        /// <param name="market">Market code (optional, default to &quot;us&quot;)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> DepopGetProductDetailAsync(string productId, string market = default(string), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Get product detail
        /// </summary>
        /// <remarks>
        /// Full detail for a single product (by numeric id or slug).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId"></param>
        /// <param name="market">Market code (optional, default to &quot;us&quot;)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DepopGetProductDetailWithHttpInfoAsync(string productId, string market = default(string), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Get shop/user profile
        /// </summary>
        /// <remarks>
        /// Public shop/user profile by username.
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username"></param>
        /// <param name="market">Market code (optional, default to &quot;us&quot;)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> DepopGetShopUserProfileAsync(string username, string market = default(string), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Get shop/user profile
        /// </summary>
        /// <remarks>
        /// Public shop/user profile by username.
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username"></param>
        /// <param name="market">Market code (optional, default to &quot;us&quot;)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DepopGetShopUserProfileWithHttpInfoAsync(string username, string market = default(string), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// List markets
        /// </summary>
        /// <remarks>
        /// List supported Depop markets (country + currency).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> DepopListMarketsAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// List markets
        /// </summary>
        /// <remarks>
        /// List supported Depop markets (country + currency).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DepopListMarketsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Search Depop products
        /// </summary>
        /// <remarks>
        /// Search the Depop catalog with filters (cursor-paginated).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search text, e.g. &#39;nike vintage&#39;</param>
        /// <param name="market">Market code (us, gb, au, it, fr, ...) (optional, default to &quot;us&quot;)</param>
        /// <param name="perPage">Results per page (optional, default to 24)</param>
        /// <param name="cursor">Pagination cursor (from previous page) (optional)</param>
        /// <param name="priceMin">Minimum price (optional)</param>
        /// <param name="priceMax">Maximum price (optional)</param>
        /// <param name="brands">Comma-separated brand IDs (optional)</param>
        /// <param name="categories">Comma-separated category IDs (optional)</param>
        /// <param name="sizes">Comma-separated size IDs (optional)</param>
        /// <param name="conditions">Comma-separated condition slugs (brand_new, used_excellent, ...) (optional)</param>
        /// <param name="gender">male | female (optional)</param>
        /// <param name="sort">relevance | newlyListed | priceAscending | priceDescending (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> DepopSearchDepopProductsAsync(string query, string market = default(string), int? perPage = default(int?), string cursor = default(string), decimal? priceMin = default(decimal?), decimal? priceMax = default(decimal?), string brands = default(string), string categories = default(string), string sizes = default(string), string conditions = default(string), string gender = default(string), string sort = default(string), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Search Depop products
        /// </summary>
        /// <remarks>
        /// Search the Depop catalog with filters (cursor-paginated).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search text, e.g. &#39;nike vintage&#39;</param>
        /// <param name="market">Market code (us, gb, au, it, fr, ...) (optional, default to &quot;us&quot;)</param>
        /// <param name="perPage">Results per page (optional, default to 24)</param>
        /// <param name="cursor">Pagination cursor (from previous page) (optional)</param>
        /// <param name="priceMin">Minimum price (optional)</param>
        /// <param name="priceMax">Maximum price (optional)</param>
        /// <param name="brands">Comma-separated brand IDs (optional)</param>
        /// <param name="categories">Comma-separated category IDs (optional)</param>
        /// <param name="sizes">Comma-separated size IDs (optional)</param>
        /// <param name="conditions">Comma-separated condition slugs (brand_new, used_excellent, ...) (optional)</param>
        /// <param name="gender">male | female (optional)</param>
        /// <param name="sort">relevance | newlyListed | priceAscending | priceDescending (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DepopSearchDepopProductsWithHttpInfoAsync(string query, string market = default(string), int? perPage = default(int?), string cursor = default(string), decimal? priceMin = default(decimal?), decimal? priceMax = default(decimal?), string brands = default(string), string categories = default(string), string sizes = default(string), string conditions = default(string), string gender = default(string), string sort = default(string), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDepopApi : IDepopApiSync, IDepopApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DepopApi : IDisposable, IDepopApi
    {
        private ScrapeBadger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DepopApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public DepopApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DepopApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public DepopApi(string basePath)
        {
            this.Configuration = ScrapeBadger.Client.Configuration.MergeConfigurations(
                ScrapeBadger.Client.GlobalConfiguration.Instance,
                new ScrapeBadger.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new ScrapeBadger.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = ScrapeBadger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DepopApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public DepopApi(ScrapeBadger.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = ScrapeBadger.Client.Configuration.MergeConfigurations(
                ScrapeBadger.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new ScrapeBadger.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = ScrapeBadger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DepopApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public DepopApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DepopApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public DepopApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = ScrapeBadger.Client.Configuration.MergeConfigurations(
                ScrapeBadger.Client.GlobalConfiguration.Instance,
                new ScrapeBadger.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new ScrapeBadger.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = ScrapeBadger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DepopApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public DepopApi(HttpClient client, ScrapeBadger.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = ScrapeBadger.Client.Configuration.MergeConfigurations(
                ScrapeBadger.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new ScrapeBadger.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = ScrapeBadger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DepopApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public DepopApi(ScrapeBadger.Client.ISynchronousClient client, ScrapeBadger.Client.IAsynchronousClient asyncClient, ScrapeBadger.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = ScrapeBadger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public ScrapeBadger.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public ScrapeBadger.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public ScrapeBadger.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public ScrapeBadger.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ScrapeBadger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Depop scraper health check Check health of the Depop scraper service (accepts HEAD).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Object</returns>
        public Object DepopDepopScraperHealthCheck()
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = DepopDepopScraperHealthCheckWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Depop scraper health check Check health of the Depop scraper service (accepts HEAD).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object</returns>
        public ScrapeBadger.Client.ApiResponse<Object> DepopDepopScraperHealthCheckWithHttpInfo()
        {
            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/v1/depop/health", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DepopDepopScraperHealthCheck", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Depop scraper health check Check health of the Depop scraper service (accepts HEAD).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> DepopDepopScraperHealthCheckAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = await DepopDepopScraperHealthCheckWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Depop scraper health check Check health of the Depop scraper service (accepts HEAD).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ScrapeBadger.Client.ApiResponse<Object>> DepopDepopScraperHealthCheckWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/v1/depop/health", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DepopDepopScraperHealthCheck", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Depop scraper health check Check health of the Depop scraper service (accepts HEAD).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Object</returns>
        public Object DepopDepopScraperHealthCheckHead()
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = DepopDepopScraperHealthCheckHeadWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Depop scraper health check Check health of the Depop scraper service (accepts HEAD).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object</returns>
        public ScrapeBadger.Client.ApiResponse<Object> DepopDepopScraperHealthCheckHeadWithHttpInfo()
        {
            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Head<Object>("/v1/depop/health", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DepopDepopScraperHealthCheckHead", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Depop scraper health check Check health of the Depop scraper service (accepts HEAD).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> DepopDepopScraperHealthCheckHeadAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = await DepopDepopScraperHealthCheckHeadWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Depop scraper health check Check health of the Depop scraper service (accepts HEAD).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ScrapeBadger.Client.ApiResponse<Object>> DepopDepopScraperHealthCheckHeadWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.HeadAsync<Object>("/v1/depop/health", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DepopDepopScraperHealthCheckHead", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get a user&#39;s products A user&#39;s active listings (cursor-paginated).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username"></param>
        /// <param name="market">Market code (optional, default to &quot;us&quot;)</param>
        /// <param name="perPage"> (optional, default to 24)</param>
        /// <param name="cursor">Pagination cursor (optional)</param>
        /// <returns>Object</returns>
        public Object DepopGetAUserSProducts(string username, string market = default(string), int? perPage = default(int?), string cursor = default(string))
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = DepopGetAUserSProductsWithHttpInfo(username, market, perPage, cursor);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get a user&#39;s products A user&#39;s active listings (cursor-paginated).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username"></param>
        /// <param name="market">Market code (optional, default to &quot;us&quot;)</param>
        /// <param name="perPage"> (optional, default to 24)</param>
        /// <param name="cursor">Pagination cursor (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        public ScrapeBadger.Client.ApiResponse<Object> DepopGetAUserSProductsWithHttpInfo(string username, string market = default(string), int? perPage = default(int?), string cursor = default(string))
        {
            // verify the required parameter 'username' is set
            if (username == null)
                throw new ScrapeBadger.Client.ApiException(400, "Missing required parameter 'username' when calling DepopApi->DepopGetAUserSProducts");

            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("username", ScrapeBadger.Client.ClientUtils.ParameterToString(username)); // path parameter
            if (market != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "market", market));
            }
            if (perPage != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "per_page", perPage));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/v1/depop/users/{username}/products", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DepopGetAUserSProducts", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get a user&#39;s products A user&#39;s active listings (cursor-paginated).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username"></param>
        /// <param name="market">Market code (optional, default to &quot;us&quot;)</param>
        /// <param name="perPage"> (optional, default to 24)</param>
        /// <param name="cursor">Pagination cursor (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> DepopGetAUserSProductsAsync(string username, string market = default(string), int? perPage = default(int?), string cursor = default(string), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = await DepopGetAUserSProductsWithHttpInfoAsync(username, market, perPage, cursor, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get a user&#39;s products A user&#39;s active listings (cursor-paginated).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username"></param>
        /// <param name="market">Market code (optional, default to &quot;us&quot;)</param>
        /// <param name="perPage"> (optional, default to 24)</param>
        /// <param name="cursor">Pagination cursor (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ScrapeBadger.Client.ApiResponse<Object>> DepopGetAUserSProductsWithHttpInfoAsync(string username, string market = default(string), int? perPage = default(int?), string cursor = default(string), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'username' is set
            if (username == null)
                throw new ScrapeBadger.Client.ApiException(400, "Missing required parameter 'username' when calling DepopApi->DepopGetAUserSProducts");


            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("username", ScrapeBadger.Client.ClientUtils.ParameterToString(username)); // path parameter
            if (market != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "market", market));
            }
            if (perPage != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "per_page", perPage));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/v1/depop/users/{username}/products", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DepopGetAUserSProducts", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get product detail Full detail for a single product (by numeric id or slug).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId"></param>
        /// <param name="market">Market code (optional, default to &quot;us&quot;)</param>
        /// <returns>Object</returns>
        public Object DepopGetProductDetail(string productId, string market = default(string))
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = DepopGetProductDetailWithHttpInfo(productId, market);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get product detail Full detail for a single product (by numeric id or slug).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId"></param>
        /// <param name="market">Market code (optional, default to &quot;us&quot;)</param>
        /// <returns>ApiResponse of Object</returns>
        public ScrapeBadger.Client.ApiResponse<Object> DepopGetProductDetailWithHttpInfo(string productId, string market = default(string))
        {
            // verify the required parameter 'productId' is set
            if (productId == null)
                throw new ScrapeBadger.Client.ApiException(400, "Missing required parameter 'productId' when calling DepopApi->DepopGetProductDetail");

            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("product_id", ScrapeBadger.Client.ClientUtils.ParameterToString(productId)); // path parameter
            if (market != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "market", market));
            }

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/v1/depop/products/{product_id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DepopGetProductDetail", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get product detail Full detail for a single product (by numeric id or slug).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId"></param>
        /// <param name="market">Market code (optional, default to &quot;us&quot;)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> DepopGetProductDetailAsync(string productId, string market = default(string), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = await DepopGetProductDetailWithHttpInfoAsync(productId, market, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get product detail Full detail for a single product (by numeric id or slug).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId"></param>
        /// <param name="market">Market code (optional, default to &quot;us&quot;)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ScrapeBadger.Client.ApiResponse<Object>> DepopGetProductDetailWithHttpInfoAsync(string productId, string market = default(string), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'productId' is set
            if (productId == null)
                throw new ScrapeBadger.Client.ApiException(400, "Missing required parameter 'productId' when calling DepopApi->DepopGetProductDetail");


            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("product_id", ScrapeBadger.Client.ClientUtils.ParameterToString(productId)); // path parameter
            if (market != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "market", market));
            }

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/v1/depop/products/{product_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DepopGetProductDetail", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get shop/user profile Public shop/user profile by username.
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username"></param>
        /// <param name="market">Market code (optional, default to &quot;us&quot;)</param>
        /// <returns>Object</returns>
        public Object DepopGetShopUserProfile(string username, string market = default(string))
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = DepopGetShopUserProfileWithHttpInfo(username, market);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get shop/user profile Public shop/user profile by username.
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username"></param>
        /// <param name="market">Market code (optional, default to &quot;us&quot;)</param>
        /// <returns>ApiResponse of Object</returns>
        public ScrapeBadger.Client.ApiResponse<Object> DepopGetShopUserProfileWithHttpInfo(string username, string market = default(string))
        {
            // verify the required parameter 'username' is set
            if (username == null)
                throw new ScrapeBadger.Client.ApiException(400, "Missing required parameter 'username' when calling DepopApi->DepopGetShopUserProfile");

            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("username", ScrapeBadger.Client.ClientUtils.ParameterToString(username)); // path parameter
            if (market != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "market", market));
            }

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/v1/depop/users/{username}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DepopGetShopUserProfile", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get shop/user profile Public shop/user profile by username.
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username"></param>
        /// <param name="market">Market code (optional, default to &quot;us&quot;)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> DepopGetShopUserProfileAsync(string username, string market = default(string), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = await DepopGetShopUserProfileWithHttpInfoAsync(username, market, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get shop/user profile Public shop/user profile by username.
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username"></param>
        /// <param name="market">Market code (optional, default to &quot;us&quot;)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ScrapeBadger.Client.ApiResponse<Object>> DepopGetShopUserProfileWithHttpInfoAsync(string username, string market = default(string), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'username' is set
            if (username == null)
                throw new ScrapeBadger.Client.ApiException(400, "Missing required parameter 'username' when calling DepopApi->DepopGetShopUserProfile");


            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("username", ScrapeBadger.Client.ClientUtils.ParameterToString(username)); // path parameter
            if (market != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "market", market));
            }

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/v1/depop/users/{username}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DepopGetShopUserProfile", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List markets List supported Depop markets (country + currency).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Object</returns>
        public Object DepopListMarkets()
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = DepopListMarketsWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// List markets List supported Depop markets (country + currency).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object</returns>
        public ScrapeBadger.Client.ApiResponse<Object> DepopListMarketsWithHttpInfo()
        {
            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/v1/depop/markets", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DepopListMarkets", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List markets List supported Depop markets (country + currency).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> DepopListMarketsAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = await DepopListMarketsWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List markets List supported Depop markets (country + currency).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ScrapeBadger.Client.ApiResponse<Object>> DepopListMarketsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/v1/depop/markets", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DepopListMarkets", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Search Depop products Search the Depop catalog with filters (cursor-paginated).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search text, e.g. &#39;nike vintage&#39;</param>
        /// <param name="market">Market code (us, gb, au, it, fr, ...) (optional, default to &quot;us&quot;)</param>
        /// <param name="perPage">Results per page (optional, default to 24)</param>
        /// <param name="cursor">Pagination cursor (from previous page) (optional)</param>
        /// <param name="priceMin">Minimum price (optional)</param>
        /// <param name="priceMax">Maximum price (optional)</param>
        /// <param name="brands">Comma-separated brand IDs (optional)</param>
        /// <param name="categories">Comma-separated category IDs (optional)</param>
        /// <param name="sizes">Comma-separated size IDs (optional)</param>
        /// <param name="conditions">Comma-separated condition slugs (brand_new, used_excellent, ...) (optional)</param>
        /// <param name="gender">male | female (optional)</param>
        /// <param name="sort">relevance | newlyListed | priceAscending | priceDescending (optional)</param>
        /// <returns>Object</returns>
        public Object DepopSearchDepopProducts(string query, string market = default(string), int? perPage = default(int?), string cursor = default(string), decimal? priceMin = default(decimal?), decimal? priceMax = default(decimal?), string brands = default(string), string categories = default(string), string sizes = default(string), string conditions = default(string), string gender = default(string), string sort = default(string))
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = DepopSearchDepopProductsWithHttpInfo(query, market, perPage, cursor, priceMin, priceMax, brands, categories, sizes, conditions, gender, sort);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Search Depop products Search the Depop catalog with filters (cursor-paginated).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search text, e.g. &#39;nike vintage&#39;</param>
        /// <param name="market">Market code (us, gb, au, it, fr, ...) (optional, default to &quot;us&quot;)</param>
        /// <param name="perPage">Results per page (optional, default to 24)</param>
        /// <param name="cursor">Pagination cursor (from previous page) (optional)</param>
        /// <param name="priceMin">Minimum price (optional)</param>
        /// <param name="priceMax">Maximum price (optional)</param>
        /// <param name="brands">Comma-separated brand IDs (optional)</param>
        /// <param name="categories">Comma-separated category IDs (optional)</param>
        /// <param name="sizes">Comma-separated size IDs (optional)</param>
        /// <param name="conditions">Comma-separated condition slugs (brand_new, used_excellent, ...) (optional)</param>
        /// <param name="gender">male | female (optional)</param>
        /// <param name="sort">relevance | newlyListed | priceAscending | priceDescending (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        public ScrapeBadger.Client.ApiResponse<Object> DepopSearchDepopProductsWithHttpInfo(string query, string market = default(string), int? perPage = default(int?), string cursor = default(string), decimal? priceMin = default(decimal?), decimal? priceMax = default(decimal?), string brands = default(string), string categories = default(string), string sizes = default(string), string conditions = default(string), string gender = default(string), string sort = default(string))
        {
            // verify the required parameter 'query' is set
            if (query == null)
                throw new ScrapeBadger.Client.ApiException(400, "Missing required parameter 'query' when calling DepopApi->DepopSearchDepopProducts");

            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "query", query));
            if (market != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "market", market));
            }
            if (perPage != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "per_page", perPage));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }
            if (priceMin != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "price_min", priceMin));
            }
            if (priceMax != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "price_max", priceMax));
            }
            if (brands != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "brands", brands));
            }
            if (categories != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "categories", categories));
            }
            if (sizes != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "sizes", sizes));
            }
            if (conditions != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "conditions", conditions));
            }
            if (gender != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "gender", gender));
            }
            if (sort != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "sort", sort));
            }

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/v1/depop/search", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DepopSearchDepopProducts", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Search Depop products Search the Depop catalog with filters (cursor-paginated).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search text, e.g. &#39;nike vintage&#39;</param>
        /// <param name="market">Market code (us, gb, au, it, fr, ...) (optional, default to &quot;us&quot;)</param>
        /// <param name="perPage">Results per page (optional, default to 24)</param>
        /// <param name="cursor">Pagination cursor (from previous page) (optional)</param>
        /// <param name="priceMin">Minimum price (optional)</param>
        /// <param name="priceMax">Maximum price (optional)</param>
        /// <param name="brands">Comma-separated brand IDs (optional)</param>
        /// <param name="categories">Comma-separated category IDs (optional)</param>
        /// <param name="sizes">Comma-separated size IDs (optional)</param>
        /// <param name="conditions">Comma-separated condition slugs (brand_new, used_excellent, ...) (optional)</param>
        /// <param name="gender">male | female (optional)</param>
        /// <param name="sort">relevance | newlyListed | priceAscending | priceDescending (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> DepopSearchDepopProductsAsync(string query, string market = default(string), int? perPage = default(int?), string cursor = default(string), decimal? priceMin = default(decimal?), decimal? priceMax = default(decimal?), string brands = default(string), string categories = default(string), string sizes = default(string), string conditions = default(string), string gender = default(string), string sort = default(string), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = await DepopSearchDepopProductsWithHttpInfoAsync(query, market, perPage, cursor, priceMin, priceMax, brands, categories, sizes, conditions, gender, sort, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Search Depop products Search the Depop catalog with filters (cursor-paginated).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Search text, e.g. &#39;nike vintage&#39;</param>
        /// <param name="market">Market code (us, gb, au, it, fr, ...) (optional, default to &quot;us&quot;)</param>
        /// <param name="perPage">Results per page (optional, default to 24)</param>
        /// <param name="cursor">Pagination cursor (from previous page) (optional)</param>
        /// <param name="priceMin">Minimum price (optional)</param>
        /// <param name="priceMax">Maximum price (optional)</param>
        /// <param name="brands">Comma-separated brand IDs (optional)</param>
        /// <param name="categories">Comma-separated category IDs (optional)</param>
        /// <param name="sizes">Comma-separated size IDs (optional)</param>
        /// <param name="conditions">Comma-separated condition slugs (brand_new, used_excellent, ...) (optional)</param>
        /// <param name="gender">male | female (optional)</param>
        /// <param name="sort">relevance | newlyListed | priceAscending | priceDescending (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ScrapeBadger.Client.ApiResponse<Object>> DepopSearchDepopProductsWithHttpInfoAsync(string query, string market = default(string), int? perPage = default(int?), string cursor = default(string), decimal? priceMin = default(decimal?), decimal? priceMax = default(decimal?), string brands = default(string), string categories = default(string), string sizes = default(string), string conditions = default(string), string gender = default(string), string sort = default(string), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'query' is set
            if (query == null)
                throw new ScrapeBadger.Client.ApiException(400, "Missing required parameter 'query' when calling DepopApi->DepopSearchDepopProducts");


            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "query", query));
            if (market != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "market", market));
            }
            if (perPage != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "per_page", perPage));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }
            if (priceMin != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "price_min", priceMin));
            }
            if (priceMax != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "price_max", priceMax));
            }
            if (brands != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "brands", brands));
            }
            if (categories != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "categories", categories));
            }
            if (sizes != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "sizes", sizes));
            }
            if (conditions != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "conditions", conditions));
            }
            if (gender != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "gender", gender));
            }
            if (sort != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "sort", sort));
            }

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/v1/depop/search", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DepopSearchDepopProducts", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
