/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using ScrapeBadger.Client;
using ScrapeBadger.Model;

namespace ScrapeBadger.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRealtorApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get full property detail
        /// </summary>
        /// <remarks>
        /// Full listing detail: features, tax &amp; price history, schools, photos, agents.
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyId"></param>
        /// <param name="market">us (realtor.com) | ca (realtor.ca) (optional, default to &quot;us&quot;)</param>
        /// <returns>Object</returns>
        Object RealtorGetFullPropertyDetail(string propertyId, string market = default(string));

        /// <summary>
        /// Get full property detail
        /// </summary>
        /// <remarks>
        /// Full listing detail: features, tax &amp; price history, schools, photos, agents.
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyId"></param>
        /// <param name="market">us (realtor.com) | ca (realtor.ca) (optional, default to &quot;us&quot;)</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> RealtorGetFullPropertyDetailWithHttpInfo(string propertyId, string market = default(string));
        /// <summary>
        /// List markets
        /// </summary>
        /// <remarks>
        /// List supported Realtor markets (US &#x3D; realtor.com, CA &#x3D; realtor.ca).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Object</returns>
        Object RealtorListMarkets();

        /// <summary>
        /// List markets
        /// </summary>
        /// <remarks>
        /// List supported Realtor markets (US &#x3D; realtor.com, CA &#x3D; realtor.ca).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> RealtorListMarketsWithHttpInfo();
        /// <summary>
        /// Location autocomplete
        /// </summary>
        /// <remarks>
        /// Resolve a location query into candidate places to feed /search.
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Freetext location (city, ZIP/postal, address…)</param>
        /// <param name="market">us (realtor.com) | ca (realtor.ca) (optional, default to &quot;us&quot;)</param>
        /// <param name="limit"> (optional, default to 10)</param>
        /// <returns>Object</returns>
        Object RealtorLocationAutocomplete(string query, string market = default(string), int? limit = default(int?));

        /// <summary>
        /// Location autocomplete
        /// </summary>
        /// <remarks>
        /// Resolve a location query into candidate places to feed /search.
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Freetext location (city, ZIP/postal, address…)</param>
        /// <param name="market">us (realtor.com) | ca (realtor.ca) (optional, default to &quot;us&quot;)</param>
        /// <param name="limit"> (optional, default to 10)</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> RealtorLocationAutocompleteWithHttpInfo(string query, string market = default(string), int? limit = default(int?));
        /// <summary>
        /// Realtor scraper health check
        /// </summary>
        /// <remarks>
        /// Check health of the realtor scraper service (accepts HEAD for UptimeRobot).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Object</returns>
        Object RealtorRealtorScraperHealthCheck();

        /// <summary>
        /// Realtor scraper health check
        /// </summary>
        /// <remarks>
        /// Check health of the realtor scraper service (accepts HEAD for UptimeRobot).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> RealtorRealtorScraperHealthCheckWithHttpInfo();
        /// <summary>
        /// Realtor scraper health check
        /// </summary>
        /// <remarks>
        /// Check health of the realtor scraper service (accepts HEAD for UptimeRobot).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Object</returns>
        Object RealtorRealtorScraperHealthCheckHead();

        /// <summary>
        /// Realtor scraper health check
        /// </summary>
        /// <remarks>
        /// Check health of the realtor scraper service (accepts HEAD for UptimeRobot).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> RealtorRealtorScraperHealthCheckHeadWithHttpInfo();
        /// <summary>
        /// Search property listings
        /// </summary>
        /// <remarks>
        /// Search for-sale/for-rent/sold listings with rich filters.
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="location">&#39;Austin, TX&#39;, a ZIP, &#39;Toronto, ON&#39;… (optional)</param>
        /// <param name="market">us (realtor.com) | ca (realtor.ca) (optional, default to &quot;us&quot;)</param>
        /// <param name="status">for_sale | for_rent | sold | pending (optional, default to &quot;for_sale&quot;)</param>
        /// <param name="priceMin"> (optional)</param>
        /// <param name="priceMax"> (optional)</param>
        /// <param name="bedsMin"> (optional)</param>
        /// <param name="bathsMin"> (optional)</param>
        /// <param name="sqftMin">US only (optional)</param>
        /// <param name="sqftMax">US only (optional)</param>
        /// <param name="propertyType">US only, CSV of property types (optional)</param>
        /// <param name="sort">relevant | newest | price_low | price_high | photo_count (optional, default to &quot;relevant&quot;)</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="limit"> (optional)</param>
        /// <param name="latMin">CA bbox south (optional)</param>
        /// <param name="latMax">CA bbox north (optional)</param>
        /// <param name="lngMin">CA bbox west (optional)</param>
        /// <param name="lngMax">CA bbox east (optional)</param>
        /// <returns>Object</returns>
        Object RealtorSearchPropertyListings(string location = default(string), string market = default(string), string status = default(string), decimal? priceMin = default(decimal?), decimal? priceMax = default(decimal?), int? bedsMin = default(int?), int? bathsMin = default(int?), int? sqftMin = default(int?), int? sqftMax = default(int?), string propertyType = default(string), string sort = default(string), int? page = default(int?), int? limit = default(int?), decimal? latMin = default(decimal?), decimal? latMax = default(decimal?), decimal? lngMin = default(decimal?), decimal? lngMax = default(decimal?));

        /// <summary>
        /// Search property listings
        /// </summary>
        /// <remarks>
        /// Search for-sale/for-rent/sold listings with rich filters.
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="location">&#39;Austin, TX&#39;, a ZIP, &#39;Toronto, ON&#39;… (optional)</param>
        /// <param name="market">us (realtor.com) | ca (realtor.ca) (optional, default to &quot;us&quot;)</param>
        /// <param name="status">for_sale | for_rent | sold | pending (optional, default to &quot;for_sale&quot;)</param>
        /// <param name="priceMin"> (optional)</param>
        /// <param name="priceMax"> (optional)</param>
        /// <param name="bedsMin"> (optional)</param>
        /// <param name="bathsMin"> (optional)</param>
        /// <param name="sqftMin">US only (optional)</param>
        /// <param name="sqftMax">US only (optional)</param>
        /// <param name="propertyType">US only, CSV of property types (optional)</param>
        /// <param name="sort">relevant | newest | price_low | price_high | photo_count (optional, default to &quot;relevant&quot;)</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="limit"> (optional)</param>
        /// <param name="latMin">CA bbox south (optional)</param>
        /// <param name="latMax">CA bbox north (optional)</param>
        /// <param name="lngMin">CA bbox west (optional)</param>
        /// <param name="lngMax">CA bbox east (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> RealtorSearchPropertyListingsWithHttpInfo(string location = default(string), string market = default(string), string status = default(string), decimal? priceMin = default(decimal?), decimal? priceMax = default(decimal?), int? bedsMin = default(int?), int? bathsMin = default(int?), int? sqftMin = default(int?), int? sqftMax = default(int?), string propertyType = default(string), string sort = default(string), int? page = default(int?), int? limit = default(int?), decimal? latMin = default(decimal?), decimal? latMax = default(decimal?), decimal? lngMin = default(decimal?), decimal? lngMax = default(decimal?));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRealtorApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get full property detail
        /// </summary>
        /// <remarks>
        /// Full listing detail: features, tax &amp; price history, schools, photos, agents.
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyId"></param>
        /// <param name="market">us (realtor.com) | ca (realtor.ca) (optional, default to &quot;us&quot;)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> RealtorGetFullPropertyDetailAsync(string propertyId, string market = default(string), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Get full property detail
        /// </summary>
        /// <remarks>
        /// Full listing detail: features, tax &amp; price history, schools, photos, agents.
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyId"></param>
        /// <param name="market">us (realtor.com) | ca (realtor.ca) (optional, default to &quot;us&quot;)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> RealtorGetFullPropertyDetailWithHttpInfoAsync(string propertyId, string market = default(string), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// List markets
        /// </summary>
        /// <remarks>
        /// List supported Realtor markets (US &#x3D; realtor.com, CA &#x3D; realtor.ca).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> RealtorListMarketsAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// List markets
        /// </summary>
        /// <remarks>
        /// List supported Realtor markets (US &#x3D; realtor.com, CA &#x3D; realtor.ca).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> RealtorListMarketsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Location autocomplete
        /// </summary>
        /// <remarks>
        /// Resolve a location query into candidate places to feed /search.
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Freetext location (city, ZIP/postal, address…)</param>
        /// <param name="market">us (realtor.com) | ca (realtor.ca) (optional, default to &quot;us&quot;)</param>
        /// <param name="limit"> (optional, default to 10)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> RealtorLocationAutocompleteAsync(string query, string market = default(string), int? limit = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Location autocomplete
        /// </summary>
        /// <remarks>
        /// Resolve a location query into candidate places to feed /search.
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Freetext location (city, ZIP/postal, address…)</param>
        /// <param name="market">us (realtor.com) | ca (realtor.ca) (optional, default to &quot;us&quot;)</param>
        /// <param name="limit"> (optional, default to 10)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> RealtorLocationAutocompleteWithHttpInfoAsync(string query, string market = default(string), int? limit = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Realtor scraper health check
        /// </summary>
        /// <remarks>
        /// Check health of the realtor scraper service (accepts HEAD for UptimeRobot).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> RealtorRealtorScraperHealthCheckAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Realtor scraper health check
        /// </summary>
        /// <remarks>
        /// Check health of the realtor scraper service (accepts HEAD for UptimeRobot).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> RealtorRealtorScraperHealthCheckWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Realtor scraper health check
        /// </summary>
        /// <remarks>
        /// Check health of the realtor scraper service (accepts HEAD for UptimeRobot).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> RealtorRealtorScraperHealthCheckHeadAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Realtor scraper health check
        /// </summary>
        /// <remarks>
        /// Check health of the realtor scraper service (accepts HEAD for UptimeRobot).
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> RealtorRealtorScraperHealthCheckHeadWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Search property listings
        /// </summary>
        /// <remarks>
        /// Search for-sale/for-rent/sold listings with rich filters.
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="location">&#39;Austin, TX&#39;, a ZIP, &#39;Toronto, ON&#39;… (optional)</param>
        /// <param name="market">us (realtor.com) | ca (realtor.ca) (optional, default to &quot;us&quot;)</param>
        /// <param name="status">for_sale | for_rent | sold | pending (optional, default to &quot;for_sale&quot;)</param>
        /// <param name="priceMin"> (optional)</param>
        /// <param name="priceMax"> (optional)</param>
        /// <param name="bedsMin"> (optional)</param>
        /// <param name="bathsMin"> (optional)</param>
        /// <param name="sqftMin">US only (optional)</param>
        /// <param name="sqftMax">US only (optional)</param>
        /// <param name="propertyType">US only, CSV of property types (optional)</param>
        /// <param name="sort">relevant | newest | price_low | price_high | photo_count (optional, default to &quot;relevant&quot;)</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="limit"> (optional)</param>
        /// <param name="latMin">CA bbox south (optional)</param>
        /// <param name="latMax">CA bbox north (optional)</param>
        /// <param name="lngMin">CA bbox west (optional)</param>
        /// <param name="lngMax">CA bbox east (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> RealtorSearchPropertyListingsAsync(string location = default(string), string market = default(string), string status = default(string), decimal? priceMin = default(decimal?), decimal? priceMax = default(decimal?), int? bedsMin = default(int?), int? bathsMin = default(int?), int? sqftMin = default(int?), int? sqftMax = default(int?), string propertyType = default(string), string sort = default(string), int? page = default(int?), int? limit = default(int?), decimal? latMin = default(decimal?), decimal? latMax = default(decimal?), decimal? lngMin = default(decimal?), decimal? lngMax = default(decimal?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Search property listings
        /// </summary>
        /// <remarks>
        /// Search for-sale/for-rent/sold listings with rich filters.
        /// </remarks>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="location">&#39;Austin, TX&#39;, a ZIP, &#39;Toronto, ON&#39;… (optional)</param>
        /// <param name="market">us (realtor.com) | ca (realtor.ca) (optional, default to &quot;us&quot;)</param>
        /// <param name="status">for_sale | for_rent | sold | pending (optional, default to &quot;for_sale&quot;)</param>
        /// <param name="priceMin"> (optional)</param>
        /// <param name="priceMax"> (optional)</param>
        /// <param name="bedsMin"> (optional)</param>
        /// <param name="bathsMin"> (optional)</param>
        /// <param name="sqftMin">US only (optional)</param>
        /// <param name="sqftMax">US only (optional)</param>
        /// <param name="propertyType">US only, CSV of property types (optional)</param>
        /// <param name="sort">relevant | newest | price_low | price_high | photo_count (optional, default to &quot;relevant&quot;)</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="limit"> (optional)</param>
        /// <param name="latMin">CA bbox south (optional)</param>
        /// <param name="latMax">CA bbox north (optional)</param>
        /// <param name="lngMin">CA bbox west (optional)</param>
        /// <param name="lngMax">CA bbox east (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> RealtorSearchPropertyListingsWithHttpInfoAsync(string location = default(string), string market = default(string), string status = default(string), decimal? priceMin = default(decimal?), decimal? priceMax = default(decimal?), int? bedsMin = default(int?), int? bathsMin = default(int?), int? sqftMin = default(int?), int? sqftMax = default(int?), string propertyType = default(string), string sort = default(string), int? page = default(int?), int? limit = default(int?), decimal? latMin = default(decimal?), decimal? latMax = default(decimal?), decimal? lngMin = default(decimal?), decimal? lngMax = default(decimal?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRealtorApi : IRealtorApiSync, IRealtorApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class RealtorApi : IDisposable, IRealtorApi
    {
        private ScrapeBadger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="RealtorApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public RealtorApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RealtorApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public RealtorApi(string basePath)
        {
            this.Configuration = ScrapeBadger.Client.Configuration.MergeConfigurations(
                ScrapeBadger.Client.GlobalConfiguration.Instance,
                new ScrapeBadger.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new ScrapeBadger.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = ScrapeBadger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RealtorApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public RealtorApi(ScrapeBadger.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = ScrapeBadger.Client.Configuration.MergeConfigurations(
                ScrapeBadger.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new ScrapeBadger.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = ScrapeBadger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RealtorApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public RealtorApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RealtorApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public RealtorApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = ScrapeBadger.Client.Configuration.MergeConfigurations(
                ScrapeBadger.Client.GlobalConfiguration.Instance,
                new ScrapeBadger.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new ScrapeBadger.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = ScrapeBadger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RealtorApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public RealtorApi(HttpClient client, ScrapeBadger.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = ScrapeBadger.Client.Configuration.MergeConfigurations(
                ScrapeBadger.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new ScrapeBadger.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = ScrapeBadger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RealtorApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public RealtorApi(ScrapeBadger.Client.ISynchronousClient client, ScrapeBadger.Client.IAsynchronousClient asyncClient, ScrapeBadger.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = ScrapeBadger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public ScrapeBadger.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public ScrapeBadger.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public ScrapeBadger.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public ScrapeBadger.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ScrapeBadger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get full property detail Full listing detail: features, tax &amp; price history, schools, photos, agents.
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyId"></param>
        /// <param name="market">us (realtor.com) | ca (realtor.ca) (optional, default to &quot;us&quot;)</param>
        /// <returns>Object</returns>
        public Object RealtorGetFullPropertyDetail(string propertyId, string market = default(string))
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = RealtorGetFullPropertyDetailWithHttpInfo(propertyId, market);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get full property detail Full listing detail: features, tax &amp; price history, schools, photos, agents.
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyId"></param>
        /// <param name="market">us (realtor.com) | ca (realtor.ca) (optional, default to &quot;us&quot;)</param>
        /// <returns>ApiResponse of Object</returns>
        public ScrapeBadger.Client.ApiResponse<Object> RealtorGetFullPropertyDetailWithHttpInfo(string propertyId, string market = default(string))
        {
            // verify the required parameter 'propertyId' is set
            if (propertyId == null)
                throw new ScrapeBadger.Client.ApiException(400, "Missing required parameter 'propertyId' when calling RealtorApi->RealtorGetFullPropertyDetail");

            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("property_id", ScrapeBadger.Client.ClientUtils.ParameterToString(propertyId)); // path parameter
            if (market != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "market", market));
            }

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/v1/realtor/properties/{property_id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RealtorGetFullPropertyDetail", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get full property detail Full listing detail: features, tax &amp; price history, schools, photos, agents.
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyId"></param>
        /// <param name="market">us (realtor.com) | ca (realtor.ca) (optional, default to &quot;us&quot;)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> RealtorGetFullPropertyDetailAsync(string propertyId, string market = default(string), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = await RealtorGetFullPropertyDetailWithHttpInfoAsync(propertyId, market, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get full property detail Full listing detail: features, tax &amp; price history, schools, photos, agents.
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyId"></param>
        /// <param name="market">us (realtor.com) | ca (realtor.ca) (optional, default to &quot;us&quot;)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ScrapeBadger.Client.ApiResponse<Object>> RealtorGetFullPropertyDetailWithHttpInfoAsync(string propertyId, string market = default(string), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'propertyId' is set
            if (propertyId == null)
                throw new ScrapeBadger.Client.ApiException(400, "Missing required parameter 'propertyId' when calling RealtorApi->RealtorGetFullPropertyDetail");


            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("property_id", ScrapeBadger.Client.ClientUtils.ParameterToString(propertyId)); // path parameter
            if (market != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "market", market));
            }

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/v1/realtor/properties/{property_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RealtorGetFullPropertyDetail", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List markets List supported Realtor markets (US &#x3D; realtor.com, CA &#x3D; realtor.ca).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Object</returns>
        public Object RealtorListMarkets()
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = RealtorListMarketsWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// List markets List supported Realtor markets (US &#x3D; realtor.com, CA &#x3D; realtor.ca).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object</returns>
        public ScrapeBadger.Client.ApiResponse<Object> RealtorListMarketsWithHttpInfo()
        {
            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/v1/realtor/markets", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RealtorListMarkets", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List markets List supported Realtor markets (US &#x3D; realtor.com, CA &#x3D; realtor.ca).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> RealtorListMarketsAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = await RealtorListMarketsWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List markets List supported Realtor markets (US &#x3D; realtor.com, CA &#x3D; realtor.ca).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ScrapeBadger.Client.ApiResponse<Object>> RealtorListMarketsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/v1/realtor/markets", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RealtorListMarkets", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Location autocomplete Resolve a location query into candidate places to feed /search.
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Freetext location (city, ZIP/postal, address…)</param>
        /// <param name="market">us (realtor.com) | ca (realtor.ca) (optional, default to &quot;us&quot;)</param>
        /// <param name="limit"> (optional, default to 10)</param>
        /// <returns>Object</returns>
        public Object RealtorLocationAutocomplete(string query, string market = default(string), int? limit = default(int?))
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = RealtorLocationAutocompleteWithHttpInfo(query, market, limit);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Location autocomplete Resolve a location query into candidate places to feed /search.
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Freetext location (city, ZIP/postal, address…)</param>
        /// <param name="market">us (realtor.com) | ca (realtor.ca) (optional, default to &quot;us&quot;)</param>
        /// <param name="limit"> (optional, default to 10)</param>
        /// <returns>ApiResponse of Object</returns>
        public ScrapeBadger.Client.ApiResponse<Object> RealtorLocationAutocompleteWithHttpInfo(string query, string market = default(string), int? limit = default(int?))
        {
            // verify the required parameter 'query' is set
            if (query == null)
                throw new ScrapeBadger.Client.ApiException(400, "Missing required parameter 'query' when calling RealtorApi->RealtorLocationAutocomplete");

            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "query", query));
            if (market != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "market", market));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/v1/realtor/autocomplete", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RealtorLocationAutocomplete", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Location autocomplete Resolve a location query into candidate places to feed /search.
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Freetext location (city, ZIP/postal, address…)</param>
        /// <param name="market">us (realtor.com) | ca (realtor.ca) (optional, default to &quot;us&quot;)</param>
        /// <param name="limit"> (optional, default to 10)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> RealtorLocationAutocompleteAsync(string query, string market = default(string), int? limit = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = await RealtorLocationAutocompleteWithHttpInfoAsync(query, market, limit, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Location autocomplete Resolve a location query into candidate places to feed /search.
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">Freetext location (city, ZIP/postal, address…)</param>
        /// <param name="market">us (realtor.com) | ca (realtor.ca) (optional, default to &quot;us&quot;)</param>
        /// <param name="limit"> (optional, default to 10)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ScrapeBadger.Client.ApiResponse<Object>> RealtorLocationAutocompleteWithHttpInfoAsync(string query, string market = default(string), int? limit = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'query' is set
            if (query == null)
                throw new ScrapeBadger.Client.ApiException(400, "Missing required parameter 'query' when calling RealtorApi->RealtorLocationAutocomplete");


            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "query", query));
            if (market != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "market", market));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/v1/realtor/autocomplete", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RealtorLocationAutocomplete", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Realtor scraper health check Check health of the realtor scraper service (accepts HEAD for UptimeRobot).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Object</returns>
        public Object RealtorRealtorScraperHealthCheck()
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = RealtorRealtorScraperHealthCheckWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Realtor scraper health check Check health of the realtor scraper service (accepts HEAD for UptimeRobot).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object</returns>
        public ScrapeBadger.Client.ApiResponse<Object> RealtorRealtorScraperHealthCheckWithHttpInfo()
        {
            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/v1/realtor/health", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RealtorRealtorScraperHealthCheck", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Realtor scraper health check Check health of the realtor scraper service (accepts HEAD for UptimeRobot).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> RealtorRealtorScraperHealthCheckAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = await RealtorRealtorScraperHealthCheckWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Realtor scraper health check Check health of the realtor scraper service (accepts HEAD for UptimeRobot).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ScrapeBadger.Client.ApiResponse<Object>> RealtorRealtorScraperHealthCheckWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/v1/realtor/health", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RealtorRealtorScraperHealthCheck", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Realtor scraper health check Check health of the realtor scraper service (accepts HEAD for UptimeRobot).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Object</returns>
        public Object RealtorRealtorScraperHealthCheckHead()
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = RealtorRealtorScraperHealthCheckHeadWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Realtor scraper health check Check health of the realtor scraper service (accepts HEAD for UptimeRobot).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object</returns>
        public ScrapeBadger.Client.ApiResponse<Object> RealtorRealtorScraperHealthCheckHeadWithHttpInfo()
        {
            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Head<Object>("/v1/realtor/health", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RealtorRealtorScraperHealthCheckHead", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Realtor scraper health check Check health of the realtor scraper service (accepts HEAD for UptimeRobot).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> RealtorRealtorScraperHealthCheckHeadAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = await RealtorRealtorScraperHealthCheckHeadWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Realtor scraper health check Check health of the realtor scraper service (accepts HEAD for UptimeRobot).
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ScrapeBadger.Client.ApiResponse<Object>> RealtorRealtorScraperHealthCheckHeadWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.HeadAsync<Object>("/v1/realtor/health", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RealtorRealtorScraperHealthCheckHead", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Search property listings Search for-sale/for-rent/sold listings with rich filters.
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="location">&#39;Austin, TX&#39;, a ZIP, &#39;Toronto, ON&#39;… (optional)</param>
        /// <param name="market">us (realtor.com) | ca (realtor.ca) (optional, default to &quot;us&quot;)</param>
        /// <param name="status">for_sale | for_rent | sold | pending (optional, default to &quot;for_sale&quot;)</param>
        /// <param name="priceMin"> (optional)</param>
        /// <param name="priceMax"> (optional)</param>
        /// <param name="bedsMin"> (optional)</param>
        /// <param name="bathsMin"> (optional)</param>
        /// <param name="sqftMin">US only (optional)</param>
        /// <param name="sqftMax">US only (optional)</param>
        /// <param name="propertyType">US only, CSV of property types (optional)</param>
        /// <param name="sort">relevant | newest | price_low | price_high | photo_count (optional, default to &quot;relevant&quot;)</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="limit"> (optional)</param>
        /// <param name="latMin">CA bbox south (optional)</param>
        /// <param name="latMax">CA bbox north (optional)</param>
        /// <param name="lngMin">CA bbox west (optional)</param>
        /// <param name="lngMax">CA bbox east (optional)</param>
        /// <returns>Object</returns>
        public Object RealtorSearchPropertyListings(string location = default(string), string market = default(string), string status = default(string), decimal? priceMin = default(decimal?), decimal? priceMax = default(decimal?), int? bedsMin = default(int?), int? bathsMin = default(int?), int? sqftMin = default(int?), int? sqftMax = default(int?), string propertyType = default(string), string sort = default(string), int? page = default(int?), int? limit = default(int?), decimal? latMin = default(decimal?), decimal? latMax = default(decimal?), decimal? lngMin = default(decimal?), decimal? lngMax = default(decimal?))
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = RealtorSearchPropertyListingsWithHttpInfo(location, market, status, priceMin, priceMax, bedsMin, bathsMin, sqftMin, sqftMax, propertyType, sort, page, limit, latMin, latMax, lngMin, lngMax);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Search property listings Search for-sale/for-rent/sold listings with rich filters.
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="location">&#39;Austin, TX&#39;, a ZIP, &#39;Toronto, ON&#39;… (optional)</param>
        /// <param name="market">us (realtor.com) | ca (realtor.ca) (optional, default to &quot;us&quot;)</param>
        /// <param name="status">for_sale | for_rent | sold | pending (optional, default to &quot;for_sale&quot;)</param>
        /// <param name="priceMin"> (optional)</param>
        /// <param name="priceMax"> (optional)</param>
        /// <param name="bedsMin"> (optional)</param>
        /// <param name="bathsMin"> (optional)</param>
        /// <param name="sqftMin">US only (optional)</param>
        /// <param name="sqftMax">US only (optional)</param>
        /// <param name="propertyType">US only, CSV of property types (optional)</param>
        /// <param name="sort">relevant | newest | price_low | price_high | photo_count (optional, default to &quot;relevant&quot;)</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="limit"> (optional)</param>
        /// <param name="latMin">CA bbox south (optional)</param>
        /// <param name="latMax">CA bbox north (optional)</param>
        /// <param name="lngMin">CA bbox west (optional)</param>
        /// <param name="lngMax">CA bbox east (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        public ScrapeBadger.Client.ApiResponse<Object> RealtorSearchPropertyListingsWithHttpInfo(string location = default(string), string market = default(string), string status = default(string), decimal? priceMin = default(decimal?), decimal? priceMax = default(decimal?), int? bedsMin = default(int?), int? bathsMin = default(int?), int? sqftMin = default(int?), int? sqftMax = default(int?), string propertyType = default(string), string sort = default(string), int? page = default(int?), int? limit = default(int?), decimal? latMin = default(decimal?), decimal? latMax = default(decimal?), decimal? lngMin = default(decimal?), decimal? lngMax = default(decimal?))
        {
            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (location != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "location", location));
            }
            if (market != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "market", market));
            }
            if (status != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "status", status));
            }
            if (priceMin != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "price_min", priceMin));
            }
            if (priceMax != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "price_max", priceMax));
            }
            if (bedsMin != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "beds_min", bedsMin));
            }
            if (bathsMin != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "baths_min", bathsMin));
            }
            if (sqftMin != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "sqft_min", sqftMin));
            }
            if (sqftMax != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "sqft_max", sqftMax));
            }
            if (propertyType != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "property_type", propertyType));
            }
            if (sort != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "sort", sort));
            }
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (latMin != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "lat_min", latMin));
            }
            if (latMax != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "lat_max", latMax));
            }
            if (lngMin != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "lng_min", lngMin));
            }
            if (lngMax != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "lng_max", lngMax));
            }

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/v1/realtor/search", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RealtorSearchPropertyListings", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Search property listings Search for-sale/for-rent/sold listings with rich filters.
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="location">&#39;Austin, TX&#39;, a ZIP, &#39;Toronto, ON&#39;… (optional)</param>
        /// <param name="market">us (realtor.com) | ca (realtor.ca) (optional, default to &quot;us&quot;)</param>
        /// <param name="status">for_sale | for_rent | sold | pending (optional, default to &quot;for_sale&quot;)</param>
        /// <param name="priceMin"> (optional)</param>
        /// <param name="priceMax"> (optional)</param>
        /// <param name="bedsMin"> (optional)</param>
        /// <param name="bathsMin"> (optional)</param>
        /// <param name="sqftMin">US only (optional)</param>
        /// <param name="sqftMax">US only (optional)</param>
        /// <param name="propertyType">US only, CSV of property types (optional)</param>
        /// <param name="sort">relevant | newest | price_low | price_high | photo_count (optional, default to &quot;relevant&quot;)</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="limit"> (optional)</param>
        /// <param name="latMin">CA bbox south (optional)</param>
        /// <param name="latMax">CA bbox north (optional)</param>
        /// <param name="lngMin">CA bbox west (optional)</param>
        /// <param name="lngMax">CA bbox east (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> RealtorSearchPropertyListingsAsync(string location = default(string), string market = default(string), string status = default(string), decimal? priceMin = default(decimal?), decimal? priceMax = default(decimal?), int? bedsMin = default(int?), int? bathsMin = default(int?), int? sqftMin = default(int?), int? sqftMax = default(int?), string propertyType = default(string), string sort = default(string), int? page = default(int?), int? limit = default(int?), decimal? latMin = default(decimal?), decimal? latMax = default(decimal?), decimal? lngMin = default(decimal?), decimal? lngMax = default(decimal?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            ScrapeBadger.Client.ApiResponse<Object> localVarResponse = await RealtorSearchPropertyListingsWithHttpInfoAsync(location, market, status, priceMin, priceMax, bedsMin, bathsMin, sqftMin, sqftMax, propertyType, sort, page, limit, latMin, latMax, lngMin, lngMax, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Search property listings Search for-sale/for-rent/sold listings with rich filters.
        /// </summary>
        /// <exception cref="ScrapeBadger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="location">&#39;Austin, TX&#39;, a ZIP, &#39;Toronto, ON&#39;… (optional)</param>
        /// <param name="market">us (realtor.com) | ca (realtor.ca) (optional, default to &quot;us&quot;)</param>
        /// <param name="status">for_sale | for_rent | sold | pending (optional, default to &quot;for_sale&quot;)</param>
        /// <param name="priceMin"> (optional)</param>
        /// <param name="priceMax"> (optional)</param>
        /// <param name="bedsMin"> (optional)</param>
        /// <param name="bathsMin"> (optional)</param>
        /// <param name="sqftMin">US only (optional)</param>
        /// <param name="sqftMax">US only (optional)</param>
        /// <param name="propertyType">US only, CSV of property types (optional)</param>
        /// <param name="sort">relevant | newest | price_low | price_high | photo_count (optional, default to &quot;relevant&quot;)</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="limit"> (optional)</param>
        /// <param name="latMin">CA bbox south (optional)</param>
        /// <param name="latMax">CA bbox north (optional)</param>
        /// <param name="lngMin">CA bbox west (optional)</param>
        /// <param name="lngMax">CA bbox east (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ScrapeBadger.Client.ApiResponse<Object>> RealtorSearchPropertyListingsWithHttpInfoAsync(string location = default(string), string market = default(string), string status = default(string), decimal? priceMin = default(decimal?), decimal? priceMax = default(decimal?), int? bedsMin = default(int?), int? bathsMin = default(int?), int? sqftMin = default(int?), int? sqftMax = default(int?), string propertyType = default(string), string sort = default(string), int? page = default(int?), int? limit = default(int?), decimal? latMin = default(decimal?), decimal? latMax = default(decimal?), decimal? lngMin = default(decimal?), decimal? lngMax = default(decimal?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            ScrapeBadger.Client.RequestOptions localVarRequestOptions = new ScrapeBadger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = ScrapeBadger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ScrapeBadger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (location != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "location", location));
            }
            if (market != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "market", market));
            }
            if (status != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "status", status));
            }
            if (priceMin != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "price_min", priceMin));
            }
            if (priceMax != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "price_max", priceMax));
            }
            if (bedsMin != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "beds_min", bedsMin));
            }
            if (bathsMin != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "baths_min", bathsMin));
            }
            if (sqftMin != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "sqft_min", sqftMin));
            }
            if (sqftMax != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "sqft_max", sqftMax));
            }
            if (propertyType != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "property_type", propertyType));
            }
            if (sort != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "sort", sort));
            }
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (latMin != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "lat_min", latMin));
            }
            if (latMax != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "lat_max", latMax));
            }
            if (lngMin != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "lng_min", lngMin));
            }
            if (lngMax != null)
            {
                localVarRequestOptions.QueryParameters.Add(ScrapeBadger.Client.ClientUtils.ParameterToMultiMap("", "lng_max", lngMax));
            }

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/v1/realtor/search", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RealtorSearchPropertyListings", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
